### ISSUE TITLE
Full T2*/S0 maps use two-echo fits for voxels with one good echo

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#102]
This discussion began in #70. Here's a brief summary: the limited T2* map (`t2sa` in [fit_decay](https://github.com/ME-ICA/tedana/blob/4b9687d3e20744b71768aa83f42fc72f81859211/tedana/model/monoexponential.py#L30)) used for everything except generating the optimally combined data only includes voxels with at least two good echoes. The full T2* map (`t2saf`), which seems to just be used for optimal combination, contains values for those single-echo voxels. The values at those voxels correspond to results from models fit using just the first two echoes, which is something that I'm confused about. 

Does anyone know if this is the expected behavior? I would expect it to use the fit from all of the echoes if bad echoes are going to be used at all, rather than just the fit from the first two echoes.

BTW this applies to the full and limited S0 maps as well.

**Comment by rmarkello** [comment]
## Short answer
**Yes**, this is the expected and desired behavior&mdash;you can't measure the decay rate of a voxel with only one echo (hence why we don't try to do these sorts of fits on traditonal single-echo data!). In a more technical sense, fitting the monoexponential decay model to only one echo essentially amounts to performing a multiple regression where your design matrix consists of two constant terms: an intercept and the echo time (where we only have one!). I've plotted the IV/DV matrices out here so you can see how the IV matrix doesn't make any sense:

![short_answer](https://user-images.githubusercontent.com/14265705/43492105-49bff5d2-94dc-11e8-9a67-6c08fb710367.png)

If that's not satisfying though, I can try to explain this in a bit more detail using some more examples (who doesn't love examples?).

## Long answer
For the purpose of this example, let's assume that we have a 256 TR time series with three echos of TE 14.5, 38.5, 62.5. (This is exactly the case with the data currently used in `tedana` testing!). We're going to focus on three voxels from this dataset: one where we have good signal in all three echos (`v3`), one where we have good signal in two echos (`v2`), and one where we have good signal in only one echo (`v1`). In this case, we're defining good signal using `tedana.utils.make_adaptive_mask()`&mdash;whether that is truly a metric of "good signal" can be saved for another discussion.

Using this example framework, your question is: for voxel `v1` why would we not just use the fit estimates from only the first echo time series? Why do we include the second echo time series at all?

#### Good signal in three echos
Let's look first at the best scenario, `v3`, where we have three echos with good signal. If we plot out the data it looks like this:

![threevoxels](https://user-images.githubusercontent.com/14265705/43492639-c2f05a30-94de-11e8-89ad-251dbde77a9c.png)

You'll notice we're using the negative echo times and natural log of the voxel signal as is done in `tedana.model.fit_decay()`. So, overall this fit looks quite reasonable and we get interpretable T2* value (`t2s = 27.43`) and S0 (`s0 = 41525.05`) estimates.

#### Good signal in one echo (fit one echo)
Alright, now let's look at our bad situation, `v1`, where we only have one echo with good signal. If we plot out the data it looks like this:

![onevoxel](https://user-images.githubusercontent.com/14265705/43493193-8c69ca8e-94e1-11e8-90db-a42150aeca3e.png)

That...doesn't look great. And our T2* (`t2s = -1.55`) and S0 (`s0 = 1.04`) values are just plain wrong. (Note that for visualization purposes I'm actually jittering the values along the x-axis a bit; they should all be _exactly_ over the echo time (-14.5), but I think that looks a bit ugly so I've spread them out a bit.)

#### Good signal in one echo (fit two echos)
Now let's take that same situation, `v1`, but fit it with two echos:

![twovoxel](https://user-images.githubusercontent.com/14265705/43493198-91eee1ba-94e1-11e8-8d87-7d197ae29e1c.png)

That looks *much* more reasonable, and so do our T2* (`t2s = 17.59`) and S0 (`s0 = 26212.77`) values. Note these estimates are different than voxel `v3`, but we'd expect variation between voxels so that makes some sense! 

## Caveats + future directions
In a Gitter discussion many moons ago, @handwerkerd said:

> The static T2* map is an estimate. That estimate has a fit quality that is typically ignored in this analysis. Javier (@javiergcas) has played around a bit with using that fit quality for masking (i.e. voxels that have a lousy static fit for the T2/S0 model are only going to cause more problems in subsequent processing steps). There's no definitive way to use the fit quality, but it's a factor that might be worth keeping in mind.

That code exists [here](https://github.com/nih-fmrif/SFIM_ME/blob/ef8fae39fcaa4b7720f45cbf86825fce5268eb98/melib/meBasics.py#L381), and I think that it would be a *fantastic* idea to integrate some of that into `tedana`.

**Comment by tsalo** [comment]
@rmarkello Thanks for the simulations and the figures, and I agree that using the fit quality metric somehow would be for the best. At the very least, we could probably run some analyses on a dataset with a large number of echoes (e.g., 5) to determine which properties best predict "good signal." I'm sure something was done to figure out the thresholds used in `make_adaptive_mask` at some point, but it would be nice to have a documented rationale.

However, my question was more why we don't use all of the echoes when only one is good, since we're using bad echoes anyway. I.e., why not treat `v1` like `v3` instead of `v2`? Or just use the average across echoes for optimal combination, given that that's the only place where the full T2*/S0 maps are used (as far as I know)?

**Comment by rmarkello** [comment]
Gotcha! Yes, there is a valid answer to that question as well.

In all these cases we're fitting a regression model where the IV matrix is composed of echo times and the DV matrix is composed of time series signal. When we have multiple echoes (say, two), we basically reduce the model to fit those two echo times (`[-14.6, -38.5]`) to the _mean values_ of the different echo time series (`[mean(TE1), mean(TE2)]`, e.g., approximately `[9.25, 8.0]` from the above example). When we have only one echo, we are effectively trying to fit a regression model of a single value (`[-14.6]`) against another single value (`[9.25]`). This is not a good idea for #reasons.

So why don't we just use ALL the echos in this case --- if we only have good signal in one echo and we're going to use two anyway, is it really any different than using three? The answer is: yes, it is different, and we don't want to do that. Using all three echos will bias our results towards a *higher* T2* estimate (lower slope), which will mean when we create our optimal combination we'll end up using signal from echo time series that are "bad."

Using `v1` from the example as above, the reason for this is that the difference in signal between the second and third echo time series is going to be less than we would expect based on the decay model. In an extreme example, we might have `[14.6, 38.5, 62.5]` for our echo times and our signal would be something like `[9.25, 8.0, 8.0]`.  By the second echo, the signal has effectively already decayed to its base value, and the lack of signal change between the second and third echo is something that our model can't capture or correct for. So not only do we not gain anything by including the third echo, but we actively skew our estimates.

Let me know if that makes sense!

**Comment by tsalo** [comment]
Okay, that makes perfect sense. Thank you for going through it for me. To be honest, I had no clue how dropout was affecting signal in the bad echoes, so it's very helpful to have a better idea of what that looks like.

Still, then, it seems like we should either be using the good echo's value (without fitting) or simply drop those voxels for the optimally combined data. Do you know if using two echoes (one bad) has any benefits over those two approaches?

**Comment by rmarkello** [comment]
These are really good questions and should probably spur a larger discussion with others. I'll go ahead and respond with my own thoughts, but I'm more than happy to iterate back and forth on these points!

#### Q1: For voxels with "good" signal in only one echo series, should we just use the TE of that first echo series as the T2* value instead of fitting any sort of decay model?
My own personal opinion is no. The way "good" signal quality is determined in `make_adaptive_mask()` is not absolute. Currently the threshold for deciding whether a given voxel has "bad" signal is set as the 33rd percentile of the average signal in the first echo series: 

https://github.com/ME-ICA/tedana/blob/0c5f93dc06e5fbbbe49811fa5eb717f7ea87ec22/tedana/utils/utils.py#L195-L210

(Note: I think these thresholds were hard-coded based on a three-echo sequence and should likely be dynamic based on the number of echos, but that's an argument for another day. For now, we just mark them as "arbitrary.") 

So it's not that the echo series that are determined to be "bad" have _zero_ signal, but rather that they just miss this rather arbitrary threshold. In my mind, this means we can still use the second echo series for generating a fit&mdash;we may not get an exact estimate because we don't have amazing signal, but it's arguably better than simply using the TE of the first series (which is almost definitely **not** the true T2* value of that voxel).

#### Q2: Should we simply drop those voxels for the optmally combined data?
I would argue no for the same reason as above: it's not that we don't have _any_ signal in those voxels, we just have more limited signal. Completely omitting these voxels seems overly conservative; you have one echo series with "good" signal so you should use it! A single-echo sequence with a standard TE (~30ms) would almost completely miss this signal, so I don't see any reason not to capitalize on having that data.

What are your thoughts? Do you think that we'd be better of being more conservative? Should we potentially take a closer look at how "good" signal is calculated in `make_adaptive_mask()`? These points aren't necessarily as complicated as, say, component selection for PCA and ICA, but are nevertheless critical given they occur very early in the pipeline!

**Comment by tsalo** [comment]
Thanks again. These responses are very helpful. I'm not entirely sold on the idea of relying on a poor estimate of signal quality for some parts of the pipeline but not for others, but at least now I understand why it's set up the way it is. It seems like the appropriate next step is for us to improve the documentation so that the rationale is much clearer. We can also clean up the following section, because the loop and the way `t2ss` and `s0vs` are filled in are weird and can be easily misinterpreted (as evidenced by the fact that the docstring description of `t2ss` is _still_ "???").

https://github.com/ME-ICA/tedana/blob/0c5f93dc06e5fbbbe49811fa5eb717f7ea87ec22/tedana/model/monoexponential.py#L72-L88

And I very much agree that we need to take a closer look at `make_adaptive_mask`. Deciding how voxels with one good echo should be handled will be easier when we have more confidence in the signal quality metric.

Does anyone have access to a dataset with a large number of echoes that we could use to look into the fit quality metric and the thresholds for defining "good" signal? I think that would be a good place to start.

**Comment by emdupre** [comment]
@handwerkerd just gave me a single subject's data with five echos -- right now the plan is to get it uploaded to openNeuro and pull it in for testing. It would probably also be a good resource, here !

**Comment by tsalo** [comment]
That is *perfect*! Thanks @handwerkerd! I can close this issue and open a new one about validating `make_adaptive_mask`, since @rmarkello has answered my original question pretty thoroughly.

Also, is there an API for OpenNeuro? I briefly tried to figure out how to download datasets programmatically but couldn't find anything.

**Comment by emdupre** [comment]
It looks like you can get an API key for uploading for sure !

![screenshot from 2018-08-03 13-01-43](https://user-images.githubusercontent.com/15017191/43655645-752ec4bc-971d-11e8-9d6a-f83dd3a7c57a.png)

**Comment by emdupre** [comment]
Re the API: it looks like there's an open issue (https://github.com/OpenNeuroOrg/openneuro/issues/789) on the S3 bucket being inaccessible, so we could follow up there !

Re closing the issue: I think we can leave the `question` tag on. I actually would also love if @rmarkello would consider adding his answer to the documentation, so we could even add a `documenting` tag, too !

**Comment by emdupre** [comment]
@rmarkello, I'm going to go ahead to close this issue and open a new one for documenting your answer !

**Comment by tsalo** [comment]
I'm reopening this because I actually have some followup questions that didn't seem like they fit into any other issues. I simulated some data (see the notebook in #354 for a more detailed example) and plotted the decay plus the log data (without the "plus one" we do).
![image](https://user-images.githubusercontent.com/8228902/60739323-7e22cd00-9f2f-11e9-87b3-5f99a1d8df93.png)

It seems like everything should be fine even if there is dropout, so do we really need the adaptive mask? There are sometimes gross fluctuations where signal actually increases from one echo to the next (see [here](https://github.com/ME-ICA/tedana/issues/113#issuecomment-470143122)), and I totally think we should control for those, but is dropout actually a problem?

**Comment by handwerkerd** [comment]
Skimming the notebook, I'm not clear on where you show dropout isn't a problem. Signal decay in a homogeneous magnetic field isn't a problem & I think that's the main thing you simulated in the notebook. If you are in regions, like the orbito-frontal cortex, where we often have non-trivial magnetic susceptibility issues that cause magnetic field inhomogeneity, the signal magnitude will decrease a lot faster than if there was only signal decay. It's in those areas where a TE>50ms will sometimes have so little signal that using that data point is essentially adding noise to a model.

**Comment by tsalo** [comment]
How would signal decay affected by dropout differ from signal decay for a voxel with a short TE?

**Comment by handwerkerd** [comment]
I'm not sure what you mean by short TE. You mean a voxel with a short T2 or T2* relaxation time so that the signal decreases more rapidly by a given TE? The issue is, for any brain region with a homogeneous 3T magnetic field, one will still have a lot more signal than noise when a 50ms echo is acquired. With enough inhomogeneity, one could easily lose most signal by 50ms to the point where including a 50ms echo is almost all just adding noise to one's model fit.
I think we're talking a bit past each other & can take this of of this issue, if you prefer.

**Comment by smoia** [comment]
@handwerkerd , you're not talking alone about this, but maybe we can discuss about this doubts in #352 ?
I see we're giving similar answers there...

**Comment by tsalo** [comment]
I think it was a mistake to reopen this issue, since the original content isn't quite the same as what we're talking about here. I'll close this for now and we can shift the discussion to #352. Sorry about that!
