### ISSUE TITLE
Questions about slice timing

### ISSUE THREAD

**Issue by jrdalenberg** [ME-ICA/tedana#107]
I have several questions about slice timing:
1) I read that slice timing is important but I have a hard time understanding how it is used in preprocessing multi-echo data (using fmriprep/meica.py). Are all echo time series corrected in the same way? Or are off-sets in the echo times used? 

EDIT: Oh, I just noticed this message from fmriprep: _"Slice-timing correction is not available for multiecho BOLD data (not implemented)."_

2) Dcm2niix stores an array "SliceTiming" in the JSON files. These SliceTiming arrays are the same across all echo json-files. Doesn't the slice timing differ across echo's? 

3) I have a Philips ME data set in PAR/REC, which does not preserve slice timing (sequential descending slice order). How do I enter the slice timing manually in the JSON file? Can I simply divide TR by the number of slices and use that time interval to calculate all slice times for all echo time-series? (e.g., [5\*slicetime, 4\*slicetime, 3\*slicetime, 2\*slicetime, 1\*slicetime, 0\*slicetime])

**Comment by handwerkerd** [comment]
I'll try to partially answer this question. Slice timing matters just like it matters for any other fMRI study. If you are collecting data across a 2sec TR you want to make some sort of slice timing correction so that voxels across slices represent roughly simultaneous events. This is typically done before multi-echo denoising because slice timing differences might cause problems with the echo dependent estimates.

The slice time is generally defined as the excitation pulse time for each slice. For single echo data, that excitation time would be the same regardless of what the echo time is and the same is true when one is collecting multiple echoes after a single excitation pulse. Therefore, I would use the same slice times for all echoes. 

As for how to do this, I have't used fmriprep yet, but AFNI does correct for slice timing as part of its multi echo preprocessing pipeline. Examples 12 at: https://afni.nimh.nih.gov/pub/dist/doc/program_help/afni_proc.py.html go through the ways to preprocess multi-echo data with AFNI (with the tshift block referring to slice timing correction).

I'm not familiar with the Philips ME sequence, but make sure the slice timing isn't actually preserved in some custom dicom field. If you know it is descending order then your division approach is fine, but be aware that scanner vendors and pulse sequences can sometimes be a bit quirky in how they define ordering (i.e. it's not always obvious which direction is descending). It never hurts to ask others at Philips or elsewhere to make 100% sure you understand how they do slice ordering.

Lastly, we're trying to direct general questions about multi-echo denoising to https://neurostars.org while having the issues here focus on stuff related to this code. This is a newish idea so I'm glad to answer questions here (and we haven't really gotten questions at neurostars yet), but I figured I'd mention this.

**Comment by emdupre** [comment]
Just to wanted to chime in and agree with everything @handwerkerd said :+1: 

I'm still working to improve the integration of multi-echo in fmriprep (we have a [few issues open](https://github.com/poldracklab/fmriprep/issues?q=is%3Aissue+is%3Aopen+label%3Ame-epi)), but implementing slice timing for ME should definitely be added to that list.

If you have any follow-up questions on this, @jrdalenberg, it would be great if you could post them to [neurostars](https://neurostars.org) ! Please let me know if you encounter any issues doing so-- and thanks for reaching out !

**Comment by jrdalenberg** [comment]
Ah thanks for the insights and pointing me to neurostars @handwerkerd  @emdupre! 

Regarding Philips: we do not have the raw data in DICOM but only PAR/REC (depricated), which does not contain the timing information. Thanks for the advise. I used the info explained here: http://dbic.dartmouth.edu/wiki/index.php/Slice_Acquisition_Order
