### ISSUE TITLE
fmriprep flags etc

### ISSUE THREAD

**Issue by KevinAquino** [ME-ICA/tedana#110]
Hiya!

I am switching over to using fmriprep instead of the Meica.py pipeline -- I was wondering are there any special flags to use or examples of a fmriprep workflow?

thanks! :)

**Comment by emdupre** [comment]
Hi @KevinAquino, sorry for the delay !

Right now the "tedana pipeline" with fmriprep is still a series of independent steps, since I haven't yet had a chance to integrate it directly into the fmriprep codebase. So, the workflow is such that (1) fmriprep is run  as best fits your data i.e., with or without fieldmaps, etc (2) minimal preprocessing steps are completed -- that is, dropping the first few volumes for stabilization and applying the brain mask, and (3) running tedana.

This workflow works and in my experience yields similar results, but it is still minimally tested ! It'd be great to get your feedback if you're also using fmriprep + tedana. 

One important note -- right now tedana by default implements the ME-ICA 3.2 version of the selection criteria, but we're planning to update to the ME-ICA 2.5 version of the selection criteria and allow 3.2 only as a user-specified option. So, please do note the version of tedana that you run since the selection criteria strongly influence the denoising process. 

Hopefully this answers your question ! Let me know if anything else arises, and please know that we also check [NeuroStars](https://neurostars.org) for any issues there.

**Comment by KevinAquino** [comment]
Thank you for that @emdupre ! so it looks like there is nothing too special that we have to do to get it working! 

I will be using this for a range of acquisitions including a 1200 cohort study, so I'll be able to provide some feedback shortly! :) 

also you mentioned:

> One important note -- right now tedana by default implements the ME-ICA 3.2 version of the selection criteria, but we're planning to update to the ME-ICA 2.5 version of the selection criteria and allow 3.2 only as a user-specified option.

do you mean selection of ICs with the k-daw flag etc?

**Comment by emdupre** [comment]
Yes, exactly ! We have #84 open to document the selection process in a much more accessible way, but effectively, the criteria by which independent components are labelled as e.g., mid-K differ across selection algorithms -- you can see an example of this in #97.
