### ISSUE TITLE
suggested tedana conda environmentl yml

### ISSUE THREAD

**Issue by rcwelsh** [ME-ICA/tedana#1111]
I posted this on neurostars and someone (Steven Meisler, Penn Med postdoc) suggested I drop on tedana github as well. I did not change the distribution, so not going to do a PR, but just open as an issue. I would highly suggest this going into the readdoc.

```
name: tedana_nox
dependencies:
  - python>=3.8
  - pip
  - mdp
  - numpy
  - scikit-learn
  - scipy
  - pip:
    - mapca
    - nilearn
    - nibabel
    - tedana
```

**Comment by tsalo** [comment]
The list of dependencies and required versions are in the pyproject.toml file, so I'd prefer not to include a separate list of requirements unless absolutely necessary. What about including information about creating an environment in the installation instructions instead? Something like:

```
conda create -n tedenv python=3.10 pip
conda activate tedenv
pip install tedana
```

**Comment by rcwelsh** [comment]
Then the readthedocs needs to be corrected, because the things I list above in the yml (except for mdp which is from an older version of tedana) are in the online instructions, those say the user will need to install the packages:

https://tedana.readthedocs.io/en/stable/installation.html

_**It will be helpful to end-users (such as me) for the documentation to reflect what is actually needed then.**_

I'd also suggest a downloadable yml as well as what you have above.

**Comment by tsalo** [comment]
Absolutely, we should remove the (possibly outdated) list of dependencies from the installation instructions and simply link to the pyproject.toml file for the list of dependencies and any version restrictions that might apply.

**Comment by rcwelsh** [comment]
What ever so that end-users can install and use without too much hassle.

Good software is only as good as the usability and success of the package is measured (in part) by the size of the end-user population. Removing as many barriers to use will keep it on that path. Not all users are python programmers.

**Comment by handwerkerd** [comment]
@rcwelsh We should definitely update the documentation, but I do want to confirm that the three lines @tsalo mentions above ( https://github.com/ME-ICA/tedana/issues/1111#issuecomment-2237279583 ) works for you and lets you install tedana. If you are installing tedana in an existing python environment, then just `pip install tedana` should be all someone needs. If so, that's what we'll put in the documentation.

End-users shouldn't need to worry about dependencies because `pip` should install any missing ones.

Do you have suggestions for making this simpler?
