### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#12]
It would be great to have a logo for ME-ICA to make the repository look a little more welcoming ! Open to suggestions, but some ideas for brainstorming:

* A python, like [NiPy](http://nipype.readthedocs.io/en/latest/_static/nipype-banner-bg.png)
* A brain ! Of course.
* Some sort of time series-- is there a way to make this visually appealing ?
* Small woodland creatures. I'm not sure how it would work, but @gkiar always seems to make adorable neuroscience logos with them.

**Comment by gkiar** [comment]
Did someone say woodland critters?! 😆 

@emdupre can you tell me a bit more about the tool so I can advise?

**Comment by emdupre** [comment]
Haha ! Yes, the docs are still being updated in #11 😅 

Basically, we're using multiple echo times to classify signals (operationalized as ICA components) as neural or non-neural noise, based on their T2* decay. 

Or, for anyone who hasn't studied MRI pulse sequence development, we're [making HDR images by taking multiple pictures](https://www.popphoto.com/how-to/2008/12/how-to-create-high-dynamic-range-images) where most MRI scanners usually take one, and then using that extra definition to figure out which parts of the scene are worth paying attention to.

**Comment by gkiar** [comment]
I have many ideas.... We'll sync up :)

**Comment by dowdlelt** [comment]
Cerberus, or a hydra would be in line with the 'multi' theme. Or perhaps even a chimera, to highlight the how the signals are classified differently...

**Comment by RoshanAlii** [comment]
I feel comfortable with the below logo for ME BIDS!
![me](https://user-images.githubusercontent.com/33366883/39863992-ee1f1232-5465-11e8-83d6-1767a95523c7.png)

**Comment by emdupre** [comment]
These are great !!! 🎉  

@RoshanAlii, what would you think of incorporating some of @handwerkerd's ideas&mdash; changing the name to `tedana` and having the "signal" that the dots are indexing go down over time ? It would be super cool if it could "decay" like [T2](https://mrimaster.com/images/T2%20DECAY.png) !

**Comment by handwerkerd** [comment]
It could use more precise graphic design, but here's a merger of the two ideas. I'm also using "Tedana" as THE name, but that is probably worth some discussion outside of just thoughts on logo-design. I decided to do the fade in the letters, which I think looks nice in a logo with a colored background. Note that I intentionally didn't make the dots fit perfectly on the "decay" curve since this is all about estimating that curve with noisy data.
![tedana logo mockup2](https://user-images.githubusercontent.com/7406227/39888588-38978946-5463-11e8-819f-43ca4fe91f1b.png)

**Comment by emdupre** [comment]
That looks amazing, @handwerkerd ! 😍 

We should make a square version, too&mdash; maybe with just the T and the decay curve, somehow ? I don't know if there's a way for you to share that image file, but if @RoshanAlii is interested in tweaking, it would be great to work on the same copy !

**Comment by handwerkerd** [comment]
Here's a square version. The top right looks a bit empty, but it feels like throwing a brain or something else there would make it cluttered. I'm creating these in Abobe Illustrator and can easily share .ai or .eps versions. If there's interest in working off this design then I guess I can attached a version here in whatever format @RoshanAlii prefers.
![tedana logo mockup3](https://user-images.githubusercontent.com/7406227/39889661-7ba7e156-5466-11e8-9a0c-811b0803acfe.png)

**Comment by gkiar** [comment]
Here are some modifications I thought of! A full and square version attached. Thoughts? ([Also, here is the SVG](https://www.dropbox.com/s/ahxcipcweckwt2e/tedana.svg?dl=0))

![tedana_full](https://user-images.githubusercontent.com/4883288/39930886-e230bdf0-5509-11e8-8a17-20fc2202e289.png)
![tedana_square](https://user-images.githubusercontent.com/4883288/39930890-e4233a5c-5509-11e8-8b62-d2e753441342.png)

**Comment by handwerkerd** [comment]
I like how @gkiar used font size instead of shading, but, for completeness, I wanted to throw out one where the line is a cleaner delta R2* curve vs TE and the letters represent the delta S curve vs TE. This is like the one I had above, but with a calculated instead of an hand drawn curve. I think it has potential, but I'm very open to other options as well.
![tedana logo mockup5-01](https://user-images.githubusercontent.com/7406227/39941676-52d8eaa2-552b-11e8-9ca9-5f8a8d02940d.png)

**Comment by emdupre** [comment]
These are both fantastic, @gkiar and @handwerkerd ! 😍 

@handwerkerd: What do you think about using the brighter color scheme from @gkiar and @RoshanAlii's sketches with your design ?

**Comment by emdupre** [comment]
I _really_ like that, @handwerkerd ! Pulling in some other contributors to make sure we get everyone's thoughts (not just those on thread), but I think this is close to done ! 
cc: @prantikk @tsalo @rmarkello

**Comment by prantikk** [comment]
Hey all, I think the most recent design by @handwerkerd looks great!  There was a more spartan logo of a similar sort in the meica_gui, but this is better I think.

**Comment by handwerkerd** [comment]
Since there is interest in my most recent one, I tweaked spacing and the letter color gradient slightly.
If others with more graphic design skill than I have want to improve it, you can access the Adobe Illustrator version at: https://drive.google.com/file/d/13hKVljCU5kdQoYeNgsDgsI2hj7RmLaAJ/view?usp=sharing and the same file in svgz format at: https://drive.google.com/file/d/1r0xflsvHdHNvLvMxRXAnMYXXNHUMVsZn/view?usp=sharing

![tedana logo mockup7-01](https://user-images.githubusercontent.com/7406227/40005530-223cd5c4-5766-11e8-8a44-4fff5ec56e31.png)

**Comment by KirstieJane** [comment]
I have been watching this thread and loving all the iterations! 😍😍😍

I feel like we’re converging on a great design so I just want to give my little :+1: to @handwerkerd’s logo! 

Is there a way to make one in each of the following shapes:

* square
* banner
* favicon (square but super small)

And then also maybe in black and white, greyscale, and inverted colours?

Dan - this doesn’t have to be done by you! If someone has the AI file then anyone can do the edits!

**Comment by handwerkerd** [comment]
Thank you!
The original is a square.

I tried a banner, but it's not as rectangular as I like. It would would take a bit more of the image adjustments than I have time for now to make it narrower & longer.
![tedana logo mockup7banner-01](https://user-images.githubusercontent.com/7406227/40015262-b92e7df6-5780-11e8-9023-3525eb2ebba8.png)
Here's a 72x72 version, as a 24-bit png, which, some quick googling says meets most favicon standards.
![tedana-logo-mockup7_flavicon](https://user-images.githubusercontent.com/7406227/40015295-d3782644-5780-11e8-8f49-8676984ce9cd.png)
Here's grayscale
![tedana-logo-mockup7_gs](https://user-images.githubusercontent.com/7406227/40015302-dd72d220-5780-11e8-82f2-116f6b2214ca.png)
I think inverted color might be a bit tricky since my dark background & light text version isn't a simple inversion. that might be for someone else to try.

**Comment by emdupre** [comment]
These looks great, @handwerkerd !! 🎉 What do you think if, for the favicon, we just do the line with no letters ? Since it'll be so small, I'm not sure if we'll be able to read 'tedana' in that format anyway !

**Comment by emdupre** [comment]
Amazing ✨ 

I'm going to close this, since I think we've arrived at a strong logo (with some great variants for our different needs !). I'll update the [README](https://github.com/ME-ICA/tedana/blob/master/README.md/), and get these on [our RTD site](tedana.readthedocs.io) ASAP. 

Thanks so much !!!
