### ISSUE TITLE
Versions of python that tedana works with

### ISSUE THREAD

**Issue by KevinAquino** [ME-ICA/tedana#124]
Hiya,

I can't seem to find in the documentation but it seems that the latest version works with python 3.6 , and from testing It didn't work with python2.7 -- I was getting importing errors -- I assume the syntax to import modules is slightly different in python 3.

**Comment by KevinAquino** [comment]
also: duecredit is automatically imported, and so although tedana worked it was popping up that error.

**Comment by tsalo** [comment]
I know that 3.6 is what we're developing on, and I don't think there are any plans to support 2.7, but it would be a very good idea to document that somewhere. Perhaps we could add information to the README's Installation section, along with a Shields.io badge like ![PyPI - Python Version](https://img.shields.io/pypi/pyversions/tedana.svg) to the top with the rest of the badges (as well as to the index page in the docs). If you'd be willing to open a PR with those changes, that would be awesome, but I can do it if not.

Regarding duecredit, I think it's fairly standard to make it an optional dependency, especially since you need to call your scripts in a particular way to generate duecredit bibliographies. The import error is meant to be a warning, and doesn't break anything. We can edit [due.py](https://github.com/ME-ICA/tedana/blob/cb01d725d05f0102e2da89ad50c32905c68a79fd/tedana/due.py) to make the warning more informative though. Perhaps something like "Duecredit not installed. Not able to generate citations, but still functional." We can also document optional dependencies in the README in addition to the required ones already listed.

**Comment by KirstieJane** [comment]
Thanks @KevinAquino for pointing these out!

I completely agree with @tsalo's suggestion - the badges are great, a little note in the README and maybe in the installation instructions about python 3 only.

I also find the "error" message (it is a warning as Taylor says) for duecredit really annoying. +1000000 to editing that message to make it clearer that it's an optional dependency! ✨
