### ISSUE TITLE
Reorganize tedpca to better mirror selcomps

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#166]
Since `tedpca` is now an optional decision tree, it would make sense to move to the `selection` module with `selcomps`. However, putting those two together reveals a few inconsistencies that should be smoothed out.

 As an example: why do we use an `eimask`-generated mask when computing Kappa and Rho values following `tedpca`, but not for `tedica` ?

**Comment by tsalo** [comment]
As part of this, I think the following would be good ideas:
- Move `kundu_tedpca` into `tedana.selection`.
- Fit models to PCA components and select components in `tedana_workflow`, instead of `tedpca`.
- Remove `pcastate` dictionary and pickle file. I believe that all of the relevant information is available between the mixing matrix (saved to `mepca_mix.1D`), the component maps (saved to `mepca_OC_components.nii`), and the component table. The only thing not currently tracked is the PCA variance explained, since the component table contains a "variance explained" estimated in `fitmodels_direct`. The two are definitely not the same.

**Comment by jbteves** [comment]
@tsalo @emdupre Could I update the top-level comment to reflect @tsalo's list above?
