### ISSUE TITLE
Drop PAID support from tedana workflow

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#214]
### Summary
In #210, I assumed that we wouldn't support the PAID combination method in the denoising workflow because I believe it is only valid on smoothed data and we don't want to perform denoising on smoothed or warped data. However, we do currently support PAID, which is why I'd like to discuss the possibility of removing that support. 

### Additional Detail
PAID assumes that "noise is isotropic and homogeneous throughout the image", which is only the case after smoothing. Since we don't want to perform multi-echo denoising (i.e., the `tedana` workflow) on smoothed data, I don't think that PAID should be an option for `tedana_workflow`, even though we should retain it for `t2smap_workflow`.

**Comment by emdupre** [comment]
To expand on this a little more: The idea, then, would be that T2* map generation could be used in any workflow, and in those with smoothed input data, the PAID method would be reasonable to use. But, because the `tedana_workflow` includes decomposition and denoising, we want to make sure that's performed on unsmoothed data. Is that right, @tsalo ?

If so, I think @handwerkerd and @javiergcas will have the most context for this, but I'm inclined to agree with your suggestion.

To confirm, then, concrete steps would be to remove the `ste` flag from [here](https://github.com/ME-ICA/tedana/blob/16cfa720f6202298d7587e72976c6e5e78eb904e/tedana/workflows/tedana.py#L93) (and subsequent workflow steps) but leave it in place [here](https://github.com/ME-ICA/tedana/blob/16cfa720f6202298d7587e72976c6e5e78eb904e/tedana/workflows/t2smap.py#L67) ? We would also need to update the documentation for that option in `t2smap_workflow` to explain its relative utility (and provide a reference, as we do for `t2s`).
