### ISSUE TITLE
Coordinate making and delivering OHBM poster and software demo

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#256]
### Summary

We have been selected to show off tedana 🎉 at OHBM as both a *poster* and a *software demo*.

This issue is to capture any ideas about what we'd like to show off in both of these presentations, and to coordinate who is going to make/print the poster/demo!

### Additional Detail

From the email to @emdupre:

> This is a reminder your abstract has been selected for a traditional Poster Presentation AND a Software Demonstration at the OHBM Annual Meeting being held June 09-13, 2019 in Rome, Italy. OHBM will provide space for your Software Demonstration, a large, flat LCD screen, a table, and access to power. You will be responsible for any other items needed to display your demonstration. You will be expected to present a traditional poster along with your Software Demonstration.The date/time/location of your Software Demonstration is: Thursday, June 13, 12:45-14:45 in the Auditorium Expo.

### Next Steps

* @emdupre has a poster from a previous presentation: seems like a good place to start.
* What would you most like to highlight (either in the poster or the demo?)

**Comment by jbteves** [comment]
I think it's critical to highlight @dowdlelt's static visualizations and @tsalo's refactoring work, per today's conference call. 

The visualizations greatly increase a user's ability to decode what the components mean and what their data looks like in feature space. 

The refactoring makes it easier for people to document, contribute, and test. Since OHBM should (presumably) have a lot of people interested in contributing to projects, it would be useful to highlight work to make things more contributor-friendly.

**Comment by jbteves** [comment]
@KirstieJane I don't want to edit your comment, but I would recommend the following checklists at the top of this issue, adapted from today's agenda minutes:
Portrait-oriented Poster:
- [ ] Motivation (sentence)
- [ ] Installation (box)
- [ ] Contributing (box)
- [ ] Documentation (box)-- highlight usefulness
- [ ] Representation of Pipeline (graphic)
- [ ] Known Limitations (box; maybe lumped in with below)
- [ ] Future Directions (box)
Software Demo:
- [ ] Digital representation on poster
- [ ] Run on CircleCI dataset? (approx 5 minutes)
- [ ] Outputs ready to go to show off
- [ ] Profile of results
- [ ] Demo notebooks (desired)
- [ ] Additional datasets (@dowdlelt may have some to supply)

**Comment by jbteves** [comment]
Additional notes from today's agenda: 

@emdupre is point on this, all others should be tagged to review. 

@tsalo would like to highlight the extensibility of `tedana` based on his (AWESOME) work in refactoring

General consensus to highlight @dowdlelt's figures as well, concurring with the previous call.

**Comment by emdupre** [comment]
OK, I've started drafting this and uploading versions to google drive -- the PDF (that should stay constant across versions) is [here](https://drive.google.com/file/d/1V_AHDpW07z2YYnHNuoZJlBdQEUDQiYJW/view?usp=sharing) !

**Comment by jbteves** [comment]
Should we make comments here?

**Comment by emdupre** [comment]
With a PDF it's hard to make comments on the actual document .... so yes, comments here seems like a good plan to me ! Unless anyone has any other suggestions :)

**Comment by jbteves** [comment]
Okay, awesome-looking poster! I don't have the design eye to make something that pretty. As a fun aside, I once had someone tell my poster looked "rasta;" I am not gifted at posters.  
A few quick suggestions:
1. Is it possible to make the institutional notations superscripts?
1. Could we change "Optimal Comb" -> "Optimal Combination" in the pipeline overview? Or does it not fit in the bubble when you do that? It's inconsistent with the fully spelled "combined" below. 
1. "Contributor" is repeated twice, once as a general classifier and then again as a specialization. Is that from something upstream of us? If not, could we either remove Contributor as a specialization or replace it with something else?
1. Perhaps we could notate in "Contributors" that those are just examples; there are many ways to get involved and we couldn't possibly spell them all out on the poster. 
1. Could we put a link immediately at the bottom of the "Contributors" frame linking to the CONTRIBUTING page? We can use a URL shortener, perhaps, since https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md is not exactly easy to remember.

**Comment by tsalo** [comment]
@jbteves I can share the PowerPoint I used to make that figure so you (and others) can edit it if you want. To briefly address point 2, "optimal combination" does take up too much space. Here's a possible updated version:
![image](https://user-images.githubusercontent.com/8228902/58195510-1d4c7780-7c96-11e9-87a7-6936357dc200.png)

**Comment by jbteves** [comment]
Thanks @tsalo ! I will strike that from my comment then. Would you mind sharing the powerpoint? I'm not sure if I want to edit but unfortunately this export is too low-res for me to read the smaller green bubbles on the right.

**Comment by tsalo** [comment]
@jbteves Sent via email. 

@emdupre The institutional notations seem to be off. I also agree with @jbteves' points about the contributors section, although if we want to link to the contributors page I think that should just be a smaller QR code in that section. Other than that, the poster looks great to me.

**Comment by jbteves** [comment]
That's true, I think a QR code would be better, good point.

**Comment by emdupre** [comment]
Hi guys ! I think [the poster](https://drive.google.com/file/d/1V_AHDpW07z2YYnHNuoZJlBdQEUDQiYJW/view?usp=sharing) is pretty much ready for feedback (with one section excepted), but I do have a few specific asks from folks in finishing it up:

- @KirstieJane, I'm still having some trouble with all-contributors (see #310), specifically in updating contributions of current authors. It would also be _great_ to have contributions across two lines in the table. Any ideas how to go about that ?

- @handwerkerd, I found the svg for the tedana square icon in the google drive (thank you !) but I can't find the long version that we currently include in the README. Any ideas where it might be ?

- @tsalo, I have a QR code in the demo section linking out to the [OHBM tedana repo](https://github.com/ME-ICA/tedana-ohbm-2019), and I wanted to give a short description of the notebooks you've included there. WDYT ? Is there anything in particular you'd like to say ?

**Comment by handwerkerd** [comment]
You should now be able to access the rectangular logo at: https://drive.google.com/file/d/1x2b6bEygecsCKCWjZngxdG_MT3hBllTx/view?usp=sharing

**Comment by jbteves** [comment]
@emdupre looks awesome! I particularly like the QR code with the caption of, "You?" A few quick things though:
1. On the call, we had discussed putting `tedana community` as the first author, then alphabetical. @dowdlelt @KirstieJane and myself were all in favor. 
1. Since @dowdlelt and myself joined, and we've had some users file some useful bug reports, and somebody has written some code to make additional reports, I think it's fair to say that the community is growing and I think that it's worth adjusting Motivation, Point 3, to say "tedana is a *growing* open-source,..."
1. I think that you might be underselling the refactor to a degree; it's actually pretty straightforward to drop in new fitting routines as far as I can tell, which is probably really useful since some people want bi-exponential and a handful of other fit types. We can also trivially add new decision trees. This is a big deal!
1. I also think you may be underselling the memory usage; it is dramatically decreased with the EPI mask as compared to standard input data. I believe it's reduced by 20%, but I can verify tomorrow for sure unless @dowdlelt has those numbers handy. I think we can use compelling words like "Substantially" or "dramatically."  

If I were to summarize my recommended changes with a theme, it's that you guys have accomplished a *lot* over the last year and I don't know that the poster makes it clear just how much you did and how successful you were. Great work!

**Comment by emdupre** [comment]
Thanks for the feedback, @jbteves ! This is all super helpful :smile_cat:

I've gone ahead and updated the poster -- unfortunately I got rid of the contributor QR code but it's because we added @monicayao as a contributor !! :tada: So I think we got the better deal, personally. But if you can think of another way to incorporate that information let me know.

@ME-ICA/tedana-devs , please take a look [at the poster](https://drive.google.com/file/d/1V_AHDpW07z2YYnHNuoZJlBdQEUDQiYJW/view?usp=sharing) and let me know if you have any feedback ! Thanks as always :sunflower:

**Comment by jbteves** [comment]
Looks great @emdupre ! Glad the feedback was helpful. I wonder if we could fit it back in by sliding the "Demo" section slightly up and dealing with things being uneven, but right now it looks quite clean, so I'm reluctant to do that. 

Did anybody have any thoughts on the [flow figure](https://github.com/ME-ICA/tedana/files/3248557/pipeline.pdf) I'd generated?

**Comment by handwerkerd** [comment]
I just send a few suggestions to @emdupre  directly, but I wanted to comment on the flow figure here. Flow figures have two purposes: (1) For developers to understand the details ofa pipeline (2) For users to understand the method. I think both @jbteves'  and @emdupre's are more for developers, but might be a bit confusing for a poster. If at all possible, I suggest paring down for the poster. I  prefer the one currently on the poster as a starting point, but the mentions of ME-HK data sets and GODEC and T1c-GSR are adding details and acronyms for one processing option that isn't really discussed anywhere else on the paper. Paring that back a bit might make the method easier to understand for someone who hasn't seen it before.

**Comment by jbteves** [comment]
Thanks for the pointers, @handwerkerd ! So what you really think is that we should strip down the original? Maybe leave it to masking, PCA, ICA, and that's it?

**Comment by jbteves** [comment]
I wasn't there but I assume @tsalo and @emdupre did an awesome job. Thanks, guys! Closing since it's over.
