### ISSUE TITLE
Update "Outputs of tedana" page in the docs regarding "__meica_mix.1D" in verbose option

### ISSUE THREAD

**Issue by smoia** [ME-ICA/tedana#338]
### Summary
Running tedana with the `--verbose` option returns two matrices, "__meica_mix.1D" and "meica_mix.1D", that are different. However, the difference between them might not be crystal clear from the documentation. What is the difference? Would it be possible to describe it better in the documentation?

Cheers!

**Comment by tsalo** [comment]
I can add this information to the RTD page. Just a brief summary here though:
- __meica_mix.1D is the initial mixing matrix, prior to sign determination and Kappa-based sorting.
- meica_mix.1D is the mixing matrix after it's been run through [tedana.metrics.dependence_metrics](https://tedana.readthedocs.io/en/latest/generated/tedana.metrics.dependence_metrics.html#tedana.metrics.dependence_metrics). The order of the components generally changes, as it goes from being sorted based on variance explained (i.e., the raw output from FastICA) to being sorted by Kappa. Also, the signs of the components may change in order to best match the fMRI data.

**Comment by jbteves** [comment]
I agree with just not writing it out then. Thanks for pointing this out @smoia

**Comment by jbteves** [comment]
@smoia I'm going to close this issue in favor of opening one to not write out `__meica_mix.1d`: see #339. Thanks again for bringing this up!
