### ISSUE TITLE
Documentation Submission Procedure

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#343]
### Summary
We would like to lower the barrier to entry for submitting documentation following OHBM feedback and comments by @handwerkerd about the difficulty of working in GitHub.

### Additional Detail
Currently, users must fork the entire repo, create a branch, and open a pull request to submit documentation patches. This is incredibly cumbersome for somebody to recommend a change for documentation, which typically requires only minimal review and testing. 

*UPDATE*: per the July 24th call, we have decided to adopt a patch submission procedure where people can e-mail an address and have the change submitted on their behalf by a core developer. 

### Next Steps
- [x] @ME-ICA/tedana-devs should respond with their opinions about possible documentation submission procedures
- [x] We should come to a consensus about the best way to handle it
- [ ] CONTRIBUTING should be updated with the new policy

**Comment by emdupre** [comment]
Sorry, I know I missed the last call -- was just editing in the online UI considered ? That seems like the easiest solution, but is the concern that it's not currently well-documented ?

**Comment by jbteves** [comment]
So the concern is that forking, branching, and then making a change is what's complicated. For code it makes perfect sense, because typically people supplying code should be familiar with that workflow or can easily follow the commands to do so. For people doing documentation, however, that may not be the case. @handwerkerd, @tsalo, or @dowdlelt please correct me if I've misrepresented the consensus of the meeting.

**Comment by handwerkerd** [comment]
That's pretty much it. You can't even submit a minor edit to the documentation text without going through the entire pull request process.
The two perspectives at the meeting were:
1. Should the documentation editing procedure be moved outside of the repository so that it's possible to do something closer to wiki-styling editing? This would make documentation editing accessible to many more people, but at the expense of having an easy way to link the documentation to tedana.readthedocs. 
2. Keeping the documentation within the full repository will keep the smooth link to tedana.readthedocs and will also provide a way to get people familiar with submitting GitHub PRs so that someone who makes documentation pull requests will develop the skills to also make code pull requests. The obvious minus of this is that it's setting up a higher barrier before someone who wants to contribute can contribute.

The general consensus seemed to be closer to (2), but with a goal of figuring out how to lower the bar to entry. Would having an email address where someone who wants to make a few suggestions without joining GitHub, gitter, etc be useful? Should the goal of that contact point be to guide people through submitting their own pull requests or just creating a PR based on someone else's edits? A few other options were discussed, but this should hopefully explain the general framework of the discussion.

**Comment by emdupre** [comment]
Wait, I think something was lost here: the online UI lets you skip all of those steps and edit in the browser. My question is whether that was considered ?

**Comment by jbteves** [comment]
Aaaaah, I didn’t realize you could propose the change on the original repo. This solution has my vote for sure.

**Comment by emdupre** [comment]
Maybe we could just better document this option 😉

Would that address your concerns, @handwerkerd ?

**Comment by handwerkerd** [comment]
I played with this a while back. You can't make changes directly to the protected master branch so you're still stuck making a branch and submitting a pull request. I'm not sure if it would be possible for someone to make a branch off the master instead of forking the whole repository first. If not, then this doesn't actually make the hard parts of submitting changes through git any easier. Like I implied, I'm fine keeping this hard & giving guidelines & a contact email/location to help people, but I'm not sure using the website UI makes this easier.

One other option that's more in line with approach (1) is to move a bunch of the non-tedana specific documentation to a google doc. We can embed links to web-published versions of the google docs into the documentation so that it would potentially look coherent throughout tedana.readthedocs, but editing certain sections would actually happen on a google doc rather than in the repository. Next time I play with documentation edits, I'll see how this looks with the google spreadsheet of articles that we already link to.

**Comment by jbteves** [comment]
Per the July 24th call, we have decided to adopt a patch submission procedure where people can e-mail an address and have the change submitted on their behalf by a core developer.

**Comment by emdupre** [comment]
Re-opening since I have some unaddressed comments on #374 -- I can open a new PR to (re-) close this with those additions !

**Comment by emdupre** [comment]
Actually, going to re-close this and add in my request for clarification on #372.
