### ISSUE TITLE
Question regarding number of echoes / max echo time

### ISSUE THREAD

**Issue by cjl2007** [ME-ICA/tedana#352]
Hi - I am experimenting a bit with some multi-echo acquisitions with a high number of echoes, 8 total. 

I understand that the majority of the signal of interest has been lost in most brain areas for these later echoes, but I wanted to test empirically at what point there is no benefit to adding echoes. 

I am surprised to see that tedana fails to identify any bold like components when using all 8 echoes, but does if I include the first ~5. 

Is there some limit within tedana, either in terms of the number of echoes or the latest echo time, that I should keep in mind? 

Thanks

**Comment by tsalo** [comment]
It is much more likely that the decision tree is just very brittle, which is something we're trying to work on. If you look at the component table, are most of the components being rejected because of I007, I009, or I010? Those are "mid-kappa" rejections, which tend to be the most problematic.

**Comment by cjl2007** [comment]
I006, actually (“ no good components found).

It worked properly when including 5 and 6 echoes total. Rerunning now with 7 total. The “no bold components” message was from my first attempt, when I included all 8.

**Comment by tsalo** [comment]
Okay, that still fits though. I006 occurs after the "absolute" classifications (i.e., classifications that occur independently for each component and don't depend on metrics from other components) at the beginning of the "relative" classifications. These "relative" classifications use things like elbows across components in the metrics to identify good/bad components, and seem to be the most finicky.

**Comment by smoia** [comment]
@cjl2007 , can I ask you what are your echo times? And also which metric are you using (mle, kundu, ...)?
I was running MEICA with 7 without any problem, but the last one was still in the 80-85 ms range.

@tsalo, shouldn't this be taken care of by the adaptive t2s mask? that's what I understood previously...

**Comment by cjl2007** [comment]
Echoes = 13.40,31.11,48.82,66.53,84.24,101.95,119.66,137.77
I was using the Kundu option.

**Comment by smoia** [comment]
And how many components do you have?

**Comment by tsalo** [comment]
@smoia The adaptive mask isn't used in metric calculation. I believe that it's only used for T2*/S0 calculation, which are only used for optimal combination. Since optimal combination is a weighted average where no weights are ever zero, echoes affected by dropout still contribute to the optimally combined data.

Technically T2* _is_ used in fitting the TE-dependence model, but since it's a constant it actually has no impact. Plus, since the adaptive mask isn't used, all echoes are included for the metric calculation.

**Comment by smoia** [comment]
I see @tsalo , now I understand, thank you!

**Comment by cjl2007** [comment]
@smoia, Re: number of components, I don't remember exactly, I have been rerunning (and overwriting; which was not wise in retrospect) using incrementally fewer echoes to get a sense of how the decision tree will behave. My memory is that it was between ~150-300. I have 450 time points total. 
Which option (mle, kundu, kundu-stab.) were you using for your 7 echo dataset? Out of curiosity.

**Comment by tsalo** [comment]
@cjl2007 have you been testing random subsets of echoes or just the first `n`?

**Comment by cjl2007** [comment]
first n,  e.g., 1-5, 1-6, 1-7...

**Comment by smoia** [comment]
@cjl2007 to be totally honest, I was using meica version 3.2 (different repo, and I guess an option that is not implemented in this tedana). However keep in mind that my last echo was well below 100ms.
In fact, I think the issue here is not number of echoes (my wild guess is that finer sampling would give you a better parameter estimation), but maximum echo time. Both tedpca with the kundu strategy and the tedica may fail due to the last echoes throwing off the (hypothetical) linear relationship between R2* and TE, hence moving a lot of your components in the "high rho" area, or worse making it difficult to find a good threshold for the submodels (elbow of the distrbution). To be sure about it I would need to see some components, the original data, the optimally combined volume and a t2s map, but that's my speculation. If you want to use all of your echoes (and here's a good question: why do you want to use all of them?), you might want to try with MLE initialisation, despite the huge number of components this option will return to you.
I'd like to see what other people think about this though!

**Comment by tsalo** [comment]
@smoia is max echo time an issue though? I reopened an issue that touched on how dropout impacts things [here](https://github.com/ME-ICA/tedana/issues/102#issuecomment-508832381) and I'm not convinced it is a problem (at least not based on one simulation).

**Comment by cjl2007** [comment]
Yeah, that sounds reasonable. Maybe I will give MLE a go. 

That is a good question ... it is a bit exploratory at this point, honestly. The main motivation was a project I have been working on, testing if multi-echo fMRI can be used to improve the reliability of resting-state functional connectivity patterns in individuals ... it seems that it can, and that the main benefit is from the optimal combination of echoes ...and recovery of signal in brain areas with short/long T2* . So, I was interested in collecting some additional echoes, so I could ask some follow up questions related to this initial finding. It also seems that may be a reduction in thermal noise from the optimal combination process, so I was curious to see if more echoes helped with respect to that as well.

**Comment by smoia** [comment]
(off-topic) I'm actually working on something very similar to that too!
Can you give me your reference by email (s.moia@bcbl.eu)?
(end off-topic)

Again, my wild guess is that the "help" comes up to a certain point in time, after which it doesn't any more.
Let's not confuse *more echoes* with *longer TE* though. Two different things.
I would be positively surprised if MLE manage to give you good components anyway, but by eliminating one kappa/rho dependent threshold estimation it might help you with the issue.

**Comment by smoia** [comment]
@tsalo , reasoning behind wild guess:
 - the submodels should be computed against Signal Percentage Change
 - in simulations without noise you can theoretically go on ad infinitum with your linear relation between R2* and TE, because minimal signal changes make your SPC tend to infinity.
 - my guess is that dropout lowers your SNR at later TEs, so
 - in real data, your SPC fluctuations might be related to noise rather than to signal
 - if this is the case, you might loose your linear relationship > wrongly estimate kappa and rho.

This said, in CEST it is becoming quite late for such speculations, so I might be totally wrong...

**Comment by tsalo** [comment]
The submodels are computed against unnormalized parameter estimates, so I don't think that the inflation of SPC as signal tends toward zero should be an issue.

I have noticed that rho seems inflated some new [component-based simulations](https://github.com/ME-ICA/tedana/blob/10b4b68b35bd41961e99bef87fcb43d9984088ca/docs/_static/plot_metric_simulations.ipynb) (see the last figure), which is weird considering that kappa is consistently way higher than rho in real data (even for components that seem like they should definitely be TE-independent).

**Comment by smoia** [comment]
@tsalo , You're right, the issue should be less prominent when you're not using SPC, but it should still be noisy.
I really need to take my time and read the code thoroughly before being able to discuss about this again. That will take some time, sorry.

**Comment by handwerkerd** [comment]
@cj2007, For each echo, have you calculated the SNR (signal in brain / outside brain) and TSNR (mean across time / stdev across time for each voxel). With echo times over 100ms, my suspicion is that most of the brain will have very low SNR and TSNR to the point where you are just adding noise by including them in an analysis. This relates to the brittleness of the current tedana code because it is possible to identify voxels where the later echoes just add noise & to ignore those echoes, but the current code doesn't yet do that.
When I have acquired 8 echoes, I increased in-slice acceleration (GRAPPA,ASSET,etc) so that all 8 were acquired in less than ~80ms. There is a balance here because I'm getting a more useful 8th echo at the expense of making all my earlier echoes a bit noisier due to acceleration. The write balance between acceleration, number of echos, and max useful echo time has not been empirically tested yet and may vary depending on how the data are processed. There's a bit more written about this at: https://tedana.readthedocs.io/en/latest/multi-echo.html#acquisition-parameter-recommendations

**Comment by cjl2007** [comment]
@handwerkerd - That is a good suggestion and I will look into calculating the SNR/TSNR. 

I knew going into this test acquisition that the echoes longer than ~100ms might not be useful, but I did not anticipate a scenario where they would actually be "harmful" (ie., add noise to the model). I think I was assuming that the echoes contributing noise would be down weighted in some way. But in retrospect, it makes sense. If I give this attempt at collecting 8 echoes another go, I will first make sure they are acquired in shorter span of time, like you suggest. 

This was a useful conversation, thank you!

**Comment by tsalo** [comment]
@handwerkerd Should we just use the adaptive mask for optimal combination and metric calculation (on top of T2*/S0 estimation)? It would put more pressure on us to make sure that the adaptive mask code is good, but it would also mean automatically excluding bad echoes when they could be harmful. 

I started playing around with it on a fork and it shouldn't be too hard to implement.

**Comment by handwerkerd** [comment]
@tsalo, This is definitely a feature we want to add, but I'm not sure where it fits in the priority list. It will involve both writing the code & testing in on data with noisier echoes. If you think it's relatively easy for you to add, then it won't hurt.

**Comment by tsalo** [comment]
I've opened a PR (#358) that should do just that.
