### ISSUE TITLE
With current master branch, kundu-stabilize option rejects all PCA components with P005 code

### ISSUE THREAD

**Issue by smoia** [ME-ICA/tedana#363]
### Summary
Running tedana version [`6cc2cdad98bef7893645a73ea7fe22b3e648d0e2`](https://github.com/ME-ICA/tedana/tree/6cc2cdad98bef7893645a73ea7fe22b3e648d0e2), with `--tedpca kundu-stabilize` as argument, returns a PCA table of P005 for every component (and the last component with P002).

Is it an expected behaviour? It didn't happen with the latest pipy version.

**Comment by tsalo** [comment]
Could you change the version number to a link to the branch you're referring to?

**Comment by smoia** [comment]
Done! The branch is the master branch.

**Comment by tsalo** [comment]
It looks like, as of the last release, `normalized variance explained` summed to 1, but now it sums to 100. I'm looking into how this changed now.

**Comment by tsalo** [comment]
Got it. We used to override the `dependence_metrics`-based normalized variance explained (which sums to 100) with the variance explained coming from PCA (which sums to 1). We switched (probably my fault) to using the `dependence_metrics`-based values and saving the PCA-based values in a separate column (currently "original normalized variance explained"). Presumably we can either 1) normalize the `dependence_metrics`-based values to sum to 1 instead of 100 or 2) store the `dependence_metrics`-based values in a separate column and override the values with the PCA-based ones.

**Comment by tsalo** [comment]
If we do end up moving back to using the PCA-based values, we should swap out `ppca.explained_variance_` (which are raw variance values) with `ppca.explained_variance_ratio_` (proportion values). This way, when we use something like MLE where the variance explained _shouldn't_ sum to 1, it won't.
