### ISSUE TITLE
Add worked contribution example

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#372]
### Summary
Per the July 24 meeting minutes, we should create a testing page which directs users on how to test locally and a fully-worked example function. We would like to emulate the work that @KirstieJane has done with [scona](https://github.com/WhitakerLab/scona/blob/master/DEVELOPMENT_GUIDE.md#worked-example) for the worked example.

### Next Steps
- [ ] Open a PR to add this as a new file

**Comment by tsalo** [comment]
I think we should also split our contributing guidelines into a development guide (for code contributors) and a general set of guidelines for documentation/issues/etc. contributors, as scona does. Both should show up directly on the RTD site's sidebar.

Maybe we could also rename the RTD site's "contributing guidelines" (which are more about governance) to something else to reduce confusion? The Governance section could be its own page, while most of the development philosophy section could be moved into FAQs (for the questions) and the development guide (e.g., for the stuff on releasing new versions).

**Comment by emdupre** [comment]
Additionally, from #343, I'd like to include an example of contributing a "small documentation patch":

It's a really subjective idea, and I think it would help to ground it in some use-cases so that contributors can get an idea for what we mean !
One other point would be that we can also add in information -- here? or below in "contributing through Github"? -- on how to contribute through the online UI.

**Comment by tsalo** [comment]
A worked example was added in #446, but it looks like that PR was never cross-linked with this issue. Is this issue good to close?

**Comment by jbteves** [comment]
Yes, sorry, I should have added that to the "Closes" in my PR.
