### ISSUE TITLE
Patch coverage reporting

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#388]
### Summary
Coverage reports are no longer uploading from CircleCI to CodeCov.

### Additional Detail
Specifically, the upload step fails with the following:
```
#!/bin/bash -eo pipefail
curl -s https://codecov.io/bash | bash -s -- \
  -f "/tmp/src/coverage/coverage.xml" \
  -t "${CODECOV_TOKEN}" \
  -n "${CIRCLE_BUILD_NUM}" \
  -y ".codecov.yml" \
  -F "" \
  -Z || echo 'Codecov upload failed'

/bin/bash: curl: command not found
Codecov upload failed
```

### Next Steps

I'm planning to open a PR to patch this. @tsalo since you most recently modified the CircleCI config, I might ask for your review !

**Comment by jbteves** [comment]
It looks like the miniconda3 image no longer includes curl, so you have to apt-get install it to use it.

**Comment by jbteves** [comment]
Additionally, it seems that you need CircleCI 2.1 to test this, but you can't test CircleCI 2.1 locally as far as I can tell, unfortunately. I tried reverting to 2.0 but then you can't use `codecov/upload` as a step, since this is a 2.1 feature. I've opened a WIP PR #390 to try and investigate a solution.
