### ISSUE TITLE
orthogonalization of ME-ICA components

### ISSUE THREAD

**Issue by afni-rickr** [ME-ICA/tedana#39]
As it stands, tedana.py fits all components to the time series and removes the resulting fit of the bad, naughty terms.  But the 'bad' components are not orthogonal to the 'good' ones, meaning this regression still removes some of the good components (though less than it would had the good components not been in the model).

Being more conservative, one might think that if the good components are really good BOLD, it would be preferable to not remove any of them.  To avoid removing any of the good BOLD components from the data one can project the good components out of the bad ones, and then project the resulting "very bad" (clean bad? pure evil?) out of the data.

This is what afni_proc.py now does with 'tedort' (tedana.py orthogonalized terms) -combine_method choices of 'OC_tedort' (AFNI's OC (~same as tedana.py but with no masking), and passing the "pure evil" terms along to the typical linear regression block) and 'tedana_OC_tedort' (tedana.py's OC, plus passing the tedort terms to the final regression block).

What do you think @emdupre, @CesarCaballeroGaudes, @dowdlelt and @handwerkerd (to drag you all into this thread... :).  I am planning to run a comparison of 'tedana' and 'tedana_OC_tedort' tomorrow, though it will be hard to put any measure on it.  But it seems preferable to not remove any of the signal that we are really interested in.

**Comment by dowdlelt** [comment]
I like this, and look forward to contributing on the testing of this idea. I would like to add some questions and concerns to this however. 

Sometimes I notice that tedana will identify components that correlate highly with motion regressors but not remove them - thus I am inclined to include standard motion regressors (and their derivatives) in the GLM. In other cases, tedana will find a portion of a motion regressor. That is, it finds a components, identifies it as noise, but in comparing it to the motion regressors it matches to only a portion of the motion estimates (say a spike, or a part after a sharp delta in motion). At this junction, I am nervous about including motion regressors in the model - part of their timeseries is in a tedana component. Thus, if I include them in the model, they will not truly fit the noise that I want them to remove - they may in fact add noise back in!

This extends to ideas like high pass filtering - tedana tends to remove low frequency components (though, sometimes they are ignored :( ...) so should include polorts in my model, or no? Should we project out the tedana outputs from all the baseline (noise) regressors in the model? I'm not an expert with GLMs so I may be making a large, embarrassing mistake here...but it just seems foolish to have these multiple methods of 'denoising' in a model (highpass filtering, motion regression, tedana) all interacting in unknown ways. 

I think I have some basic vision and finger tapping tasks that I can test with OC_tedort - to see how things change (optimistically, improve!) If I get a chance I'll spin that up.

**Comment by emdupre** [comment]
Thanks for opening this discussion, @afni-rickr  ! So, just to make sure I'm understanding correctly, this would be just projecting out with the components, right ? Not with other regressors ? 

If we're also orthogonalizing with things like motion, as @dowdlelt suggested, I'm not sure if tedana is the right place for that, since right now the preprocessing is largely left out (for either afni_proc or FMRIPREP or some other pipeline), so there's no guarantee how the motion files will be generated / structured. 

One maybe relevant point: the idea of adding noise back in reminds me of a [similar conversation that took place on FMRIPREP](https://github.com/poldracklab/fmriprep/issues/817) a few weeks ago. The conclusion I think&mdash; though @chrisfilo can correct me if I'm wrong&mdash; was that adding back noise was unlikely.

**Comment by chrisfilo** [comment]
That's my intuition, but it should be easy to test on simulated data.

**Comment by handwerkerd** [comment]
This is partially rephrasing what @afni-rickr wrote, but the way it is currently done is all ICA components are fit to the original data to create a beta values for each component. The beta values from just the bad components are then projected out of the data to everything (including unmodeled noised) is left in the denoised time series. An issue arises if the good and bad components are not orthogonal.  Let's say the model has two components. Good component G = 7*X+2*Y. Bad component B = 2*Y + 7*Z. (X, Y & Z are orthogonal) The way noise removal is currently done, the bad component will model all of Z and half of Y. That means half of the Y signal will be removed from the denoised time series because it's variance is split between the good & bad components. In Rick's edit, before projecting out B from the data, B is orthogonalized from G so that only the Z part of B will be regressed from the data. Thus, the issue is whether we want to keep all of Y because it is in the good signal or just part of Y because it is parsed between the two signals. In this example, I'd say we want to keep it all.

Thinking about this a bit more (since the last time I spoke to Rick), if 90% of the variance a colinear signal is in bad components and 10% is in good components, I can see this orthogonalization potentially keeping signal that should have been removed. I think having this option is important, but figuring out the right setting in specific cases, might be a bit trickier.

As for regressing motion regressors or slow drifts, I think it's important to keep TE dependent analysis steps separate from other possible preprocessing decisions. For example, Evans, Kundu et al NeuroImage 2015 shows that the slow drifts can contain neural information after MEICA denoising. This program might include options for some of these non-echo dependent regressors, but I'd hesitate setting any such options as a default.

**Comment by dowdlelt** [comment]
I'll see if I can find a prime example of this issue that I am imagining, if one such example exists. @emdupre and @chrisfilo thanks for your insight (and links) on this concept. I'll peruse that thread and, if I'm lucky, assuage my fears. 

@emdupre I agree that it seems like it is a separate issue - and that is readily apparent in the original intention of the code, in which MEICA could perform filtering/norm/etc preproc before handing off to tedana. 

Frankly, I would be thrilled for tedana to be a drop in sort of solution - and I think that is in the spirit of this issue - remove noise, without impacting signal in a negative way. Fingers crossed.

**Comment by afni-rickr** [comment]
@emdupre, there are 2 projections, so I want to make sure we are talking about the same one(s).  The first projection is just with MEICA terms, projecting the good components out of the bad, resulting in the tedort "pure evil" terms.  Those are passed along to the second regression, which is a full model, including motion, drift censoring and task, and even band passing if it is requested (I am not a fan).

The way afni_proc.py is structured now, @dowdlelt 's concern should not apply, since the tedort components end up on the full regression model along with the motion parameters.  Extending to band passing and such, that is exactly why afni_proc.py does band passing, drift, other noise, and task regression, all along with censoring in one model.  That way nothing is "added back in" in a subsequent regression.

A future plan I have for tedana.py is to remove known sources of noise, along with censoring, BEFORE running tedana (it does not seem to require temporal continuity).  And then zero-pad the resulting tedort regressors and data (from any censoring) to preserve time continuity in the full model.  The point would be to not "waste tedana's effort" trying to model known motion time points and such, letting it focus more on the BOLD/non-BOLD aspect of the data.

**Comment by chrisfilo** [comment]
What @handwerkerd wrote is consistent with my findings in context of similar deicisions made in context of ICA-AROMA. My analysis can be found at https://gist.github.com/chrisfilo/dc845d1a8a229a8d660ad75c3042b419

**Comment by afni-rickr** [comment]
So @chrisfilo, does that mean we are just a year behind the times?  It feels good to be in the same decade at least...

**Comment by emdupre** [comment]
Thanks for confirming, @afni-rickr and @handwerkerd ! 

Yes, that's what I was hoping was the idea (@afni-rickr's first projection), in which case we could definitely work toward having the optional orthogonalization in tedana.

Was this something you said you had already implemented, @afni-rickr ? Would you be able to share it, so we could get a sense of how it would fit in tedana ? Pull requests are always welcome, too 😄

**Comment by afni-rickr** [comment]
Yes @emdupre, it went into AFNI a few days ago (I will not test my feeble memory on accuracy), implemented in a short and sweet shell script (to keep the user proc script more clean), [@extract_meica_ortvec](https://github.com/afni/afni/blob/master/src/scripts_install/%40extract_meica_ortvec) .  Basically, it combines accepted with ignored (having to grep IGN out of comp_table.txt) and rejected with midk_rejected, and then projects (3dTproject) the accepted from the rejected.  I don't know how to do a projection in python, though I guess you could again fit the good to each bad and subtract the resulting fit.

**Comment by chrisfilo** [comment]
In the MNI space.

**Comment by CesarCaballeroGaudes** [comment]
@chrisfilo but are regressors defined from data in the original space?

**Comment by chrisfilo** [comment]
The ICA and component classification is performed after moving the data to
the MNI space. This is necessary because ICA AROMA uses some masks in the
MNI space, and it does not support ANTs warp transforms.

On May 12, 2018 12:43 PM, "CesarCaballeroGaudes" <notifications@github.com>
wrote:

@chrisfilo <https://github.com/chrisfilo> but are regressors defined from
data in the original space?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ME-ICA/tedana/issues/39#issuecomment-388578304>, or mute
the thread

**Comment by emdupre** [comment]
Thanks for the insight, @CesarCaballeroGaudes ! If I understand your suggestions correctly, my one concern with adding in something like the ICA-AROMA criteria is that I don't think we can assume that `tedana` will have access to motion regressors, as those will be generated from preprocessing (which is not part of this package, as it was in ME-ICA).

I believe this is why @afni-rickr was suggesting that, within `tedana` itself, we would only do his "type 1" projection, which
> is just with MEICA terms, projecting the good components out of the bad, resulting in the tedort "pure evil" terms.

As to whether these are regressed before or after normalization, I think that will depend on where `tedana` is incorporated into a larger preprocessing pipeline ! I see our job as just handling the modelling, decomposition, and component selection with the supplied multi-echo data. We'll also need to make it clear to users that this works best when incorporated into a larger preprocessing pipeline (i.e., that we are not expecting to receive data straight off the scanner).

**Comment by afni-rickr** [comment]
@CesarCaballeroGaudes the difference between OC_tedort and tedana_OC_tedort (much like between OC and tedana_OC) is simply who is doing the OC, AFNI (@compute_OC_weights) or tedana.py.  The methods are based on the same equations, but AFNI does not mask anything.

Your comments about motion relate to my thoughts about projecting motion, trends and even censoring before running tedana.  If there are no motion components in the data, they will not be found by tedana.  Removing known nuisance terms before running tedana makes a lot of sense.  Let it focus on BOLD questions.  It is not clear when I will get to that.

Note that we also expect to run tedana in standard space.  Well, the user can choose of course, but this might just get back to avoiding the extra interpolation by combining all registration transformations together, which means going straight to standard space at volume registration time.

**Comment by tsalo** [comment]
I'd just like to ping everyone regarding #155, where I try to implement the orthogonalization discussed here as part of the denoising. Would someone familiar with the method mind taking a look at that PR?

**Comment by afni-rickr** [comment]
Thanks, @tsalo and @emdupre!  So the net result of applying that option would be an additional output file, meica_mix_orth.1D?  It looks good to me!  This is a nice prompt to get some testing set up here.  If you merge it, I should be able to do a quick test against my own orthogonalization.  Thanks again!

**Comment by tsalo** [comment]
That's right. The denoised data, `dn_ts_OC.nii`, will also be impacted by the regression. @emdupre walked me through the different approaches people take to the removal of bad components, and from what I understand, if you want to perform an omnibus regression that includes motion parameters and other nuisance regressors, then you would use the optimally combined data (`ts_OC.nii`). If that is the case, then `dn_ts_OC.nii` being affected shouldn't impact your approach, and `meica_mix_orth.1D` should be all you need (along with `ts_OC.nii` and the component table, of course).

On the other hand, for people who want to just use the denoised data, then the `tedort`-adjusted denoised data should be right for them.

**Comment by afni-rickr** [comment]
That sounds perfect, thanks!
But I am having a little trouble with --mask.  It looks like nilearn._utils.check_niimg() might be called from the newly created child directory (just for the mask dataset, not the -d ones), and so it might not be found.  It will probably work using full paths, but not relative ones.  Maybe tedana_workflow's os.chdir should be down a few more lines?  Thanks again!

**Comment by tsalo** [comment]
Hopefully soon we'll include out_dir as an argument to all of the functions that write out files, so we won't have to change the directory at all, but for now I'll include that change (moving `os.chdir` down) in one of my open PRs, #167. We'll probably be able to merge that one in next week, since it's mostly documentation stuff.

Thanks for weighing in, @afni-rickr.
