### ISSUE TITLE
Incorporate bounds into curvefit T2*/S0 estimation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#440]
### Summary
We can limit T2*/S0 estimates with the curvefit method to realistic values, which hopefully would improve the estimates or at least make fit failures more explicit.

### Additional Detail
T2* should always be greater than zero, and S0 should always be higher than the first echo's value. However, in the latter case, we might have noise in the data, so maybe a more reasonable limit would be the minimum value across echoes? This will be higher than zero, which is better than nothing. I don't know about maximum values, but it would be nice if we had some idea about the maximum T2* for CSF that we could use.

### Next Steps
1. Add `bounds` argument to `scipy.optimize.curve_fit` call.
2. Allow both `RuntimeError` (current) and `ValueError` (when bounds don't work with data) in except statement.

**Comment by tsalo** [comment]
@dowdlelt Would especially like your input on this.

**Comment by dowdlelt** [comment]
I tried to add bounds before I opened the pull request - but I wasn't adept at handling the errors and there were many. I think it could dramatically speed things up. For S0 I think you could use the first echoes value as a limit - even with noise, movement, etc, S0 should always be exceed that by a good bit. T2* is a bit trickier - should be above zero certainly - but what happens if our first guess from the linear fit is below. Definitely complains if your initial guess is outside of provided bounds. It gets a bit tricky I think.

**Comment by tsalo** [comment]
I tested locally and including bounds wasn't a problem as long as we add ValueError to our catch. Using the max value from the actual data as the minimum possible S0 value did cause more voxels to fail on the fit than using the min value.
