### ISSUE TITLE
Clarify communication methods for tedana

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#478]
### Summary
Currently, there are three main avenues by which we communication about tedana: 1) on the Github through issues and pull request reviews, 2) on the Gitter chat room, and 3) through the newsletter.

Thus far, I would suggest that conversation seems to move from the Gitter chat room (2), to the Github repository (1), and -- if efforts are successful in implementing some new feature or patching a bug -- they are advertised in (3) the newsletter. I don't think this is a desirable routing of information, and I'd like to strongly suggest we move to a routing that looks like (1) --> (3). This isn't to say that the Gitter chat room can't exist, but I think it shouldn't be a source of information in and of itself.

Instead, we should be primarily communicating on the Github repository, with the Gitter chat room for redirecting to existing (open or closed) Github issues / PRs. This will be especially useful as we start expanding into multiple repositories, if someone is having difficulty locating the appropriate issue. 

Previously our informal rule was that "quick" questions should go on the Gitter, but it seems that this is a subjective line and as such we've often seen extended conversations on Gitter. The problem with this is that Gitter is hard to index, and therefore information is likely to be (and has been repeatedly) lost over time.

### Additional Detail

In some of her Turing Way work, @KirstieJane has  made a great point about open source projects in general -- they're often hard to adjust to for researchers used to "conversations in the kitchen;" that is, the idea that you can quickly stop over at your colleague's desk and have a discussion on some shared research project. 

These conversations are obviously helpful for many teams working in traditional environments, but in an open source context they're actually detrimental because the information is not recorded and cannot be distributed more broadly. You therefore create working conditions where only some members of the team have access to information, making it more difficult for new contributors to onboard and for contributors in disparate time zones to feel empowered to address issues or open PRs.

I think we've fallen into a comfort zone of using Gitter for our "conversations in the kitchen." Although we could close down Gitter, I don't think this is the right approach. Instead, I'd like us to all consciously make an effort to minimize our conversations on Gitter and instead take advantage of the GitHub issue system. 

### Next Steps

I'd love to get input from @tsalo @smoia @CesarCaballeroGaudes @eurunuela @javiergcas @handwerkerd @jbteves @dowdlelt. 

We should also make sure the relevant contributing guidelines are updated accordingly.

**Comment by eurunuela** [comment]
I do see an issue here too. I think we should all make an effort to move discussions to GitHub issues so we avoid any loss of information. As it was already said during the last call we had, we all must be aware of this and kindly suggest to move Gitter conversations to GitHub as soon as they happen.

**Comment by handwerkerd** [comment]
I fully agree. The one thing that was discussed at our previous meeting & I want to stress here is that, when someone posts something on gitter that one can respond to, a first inclination is just to respond there. If a post should be an issue, I will try to either create the issue or respond asking the initial poster to create the issue. If the most frequent gitter posters get in the habit of politely re-directing conversations to GitHub issues, that would greatly help in making this change.

A policy of political redirection to GitHub issues could also be mentioned in edited contributor guidelines.

**Comment by smoia** [comment]
Hi all,
I don't have strong opinions about it. I'll happily adopt the solution you prefer!

**Comment by dowdlelt** [comment]
I think I am absolutely one of those people used to 'conversations in the kitchen', and gitter fed that habit. So, I think it is just a matter of getting used to a new approach, and some general nudges in the right direction. 

Besides, I agree that it was annoying/detrimental when I couldn't find something in an issue, realized it was because it was on gitter and then scrolled up and up on a hopeless quest to find it. Issues, despite the higher upfront time/mental cost do seem to be the right move. 

I'm on board with whatever is decided - though I do like that gitter exists, so I agree - don't get rid of it.

**Comment by jbteves** [comment]
I thought about it a little bit over break and I agree with @KirstieJane's point about conversations in the kitchen. In research that's often the fastest solution, but in software it doesn't work well because we're not all in the kitchen at the same time, so to speak.

There is also a secondary argument that asking people to stop and write something down more comprehensively to open an issue also encourages deeper thought about problems, whereas real-time chat feels a lot more like texting your science pals. 

Is there a way we could put a sort of banner at the top of Gitter indicating our feelings on this in addition to adding to guidelines? It's easy to miss if somebody just skims CONTRIBUTING quickly.

**Comment by emdupre** [comment]
We've settled into local minimums here, I think Do we want to write-up the current status and share it at https://tedana.readthedocs.io/en/stable/support.html so it's transparently documented ?

**Comment by eurunuela** [comment]
> Do we want to write-up the current status of our communication pathways and share it in [the support page of the docs](https://tedana.readthedocs.io/en/stable/support.html) so it's transparently documented ?

Sounds reasonable to me.
