### ISSUE TITLE
Modularize functions for easier testing

### ISSUE THREAD

**Issue by rmarkello** [ME-ICA/tedana#50]
I ran into an issue when writing a few of the tests in `test_utils.py` that I think is only going to get worse as we encourage writing new tests; namely, we assume that all the functions in the repo are strung together as in `tedana.workflows.tedana`. That is, we assume (1) the data are loaded (`tedana.utils.load_data`), (2) a mask is made (`tedana.utils.make_adaptive_mask`), (3) the optimal combination is created (`tedana.model.make_optcom`), (4) the T2* and S0 map are generated (`tedana.model.fit_decay`), and so on and so forth.

For the purposes of testing, this ends up becoming incredibly cumbersome because if I want to test, say, `tedana.model.fit_decay`, I need to perform the first three steps to get the appropriate input data to do so. As we move down the workflow, the individual unit tests are going to get rather bulky&mdash;we'll basically have to run the entirety of `tedana.workflows.tedana` to test, for example, `tedana.select.selcomps`.

It might be worth considering modularizing the functions a bit more to ease this burden. That is, maybe we can adopt a `nilearn._utils.check_niimg` style convention, where, regardless of what data is passed to a given function, we check that is in the appropriate shape (samples x echos x time) and then do all the necessary transformations on it within the function of interest (i.e., make a mask, generate the T2* map), rather than requiring that users supply all the various data beforehand. This still won't necessarily work for e.g., `tedana.select.selcomps`, but in that case we might consider pre-generating some of the input data (rather than going from the "raw" echos).

**Comment by tsalo** [comment]
@rmarkello Regarding conversion/masking of data to the samples x echoes x time shape, do you think that those are functions that should be incorporated into `nilearn` (e.g., `check_niimg_me`, `apply_mask_me`, and `unmask_me`)?

**Comment by rmarkello** [comment]
I don't think any of this is particularly suitable for `nilearn`, given the relatively limited use case... But perhaps that's just my perspective on what `nilearn`'s functionality is supposed to be.

The issue we're running into here is more that we're not putting *any* restrictions on the type of data users are supplying (i.e., it could be a z-concatenated nifti, it could be three niftis, it could be three giftis), so we need to have a function (currently, `tedana.utils.load_data`) to handle that. I think it might be beneficial to perhaps split that into `check_data` and `load_data` functions; the former could be used similarly to `nilearn._utils.check_niimg`, and the latter would be called if data needed to actually be loaded / coerced into the right format.

Let me know if I'm interpreting your question correctly! Apologies if not.

**Comment by tsalo** [comment]
I was thinking that the basic handling of multi-echo data should be exported to a separate, general package in order to avoid developing multiple "standards" in parallel (on the off chance other people want to develop separate tools for analyzing multi-echo data). `nilearn` includes the most commonly used tools for checking, masking, and unmasking fMRI data, although, as with its plotting module, it's unclear whether all of that falls within `nilearn`'s self-imposed domain. 

I'm certain we can write a version of `check_niimg` that works for each of the possible formats we want to support, but I don't know if it ultimately belongs in as specialized a package as `tedana`. I suppose the most appropriate next step is to write the function(s) and then to revisit the possibility of porting it over to another package at a later date. I'd be happy to take a crack at it, although I don't know anything about giftis or ciftis, unfortunately.

On a related note, I don't think we should support z-concatenated niftis. `nibabel` seems to work fine with X x Y x Z x echo x time shaped data, and the 5D format doesn't require manual specification of the TEs just to load the data.

**Comment by rmarkello** [comment]
Got it! I think....

I suppose my question is: what's the ideal shape/format for multi-echo data to be in? We're coercing it to `samples x echos x time` in order to support both volumetric + surface data, but I think that have 5D data (`X x Y x Z x echos x time`, as you suggest) is probably preferable for nifti-based data. (I actually think that `X x Y x Z x time x echos` is better, but that wasn't what the original `tedana` codebase used so we stuck with `echos` before `time`...). Are you suggesting we coerce everything to `samples x echos x time` and just generate a set of functions that operate on that? If so, :+1: :100:.

I'm totally game for there being a separate module (in my mind that's what `utils.io` *should* be) to handle all these manipulations! I think, as you said, it might be best to develop these and then revisit whether it should exist outside of `tedana`.

As for the z-concatenated data: I'd love to not support it, but for legacy purposes I think we're stuck. Hypothetically people who previously used the original `ME-ICA` could just provide the `e?_in.nii.gz` files that are generated by that pipeline and create the `zcat_ffd.nii.gz` file, but it's possible some may only have retained the z-concatenated outputs (which served as inputs to the original `tedana`). I think perhaps the appropriate course of action would be to continue developing `tedana` as is, version it, and then maybe consider integrating a `DeprecationWarning` about no longer supporting z-concatenated data. That way, users would have **a** version of `tedana` (even if it is 0.0.1) that works with the old data files.

**Comment by handwerkerd** [comment]
I think the reason the data are often in 3D samples x echoes x time is because that's a great structure for any type of matrix manipulation where spatial adjacency doesn't matter (i.e. ICA). If my memory serves, the original code used that frequently (or 2D samples x time), but bounced back to X x Y x Z x time whenever there was a volume to write and for a few selection criteria that used spatial information.

If the goal is to make this code friendly for volumes or surfaces, I'd lean towards keeping data as (samples x time) or (samples x echoes x time) with some modularized functions that make it easy to convert to volumes or surfaces and back as needed. that would help minimize the situations where the code has to include (if volume do X, if surface do Y).

As for the zcat files, that's really just an file loading issue. If there's code to read zcat files or separate files for each echo, into the same data structure, I see no reason to ever remove the zcat reading option (breaking backwards compatibility), but there might be a time when that option doesn't need to be highlighted in the help documentation.

**Comment by rmarkello** [comment]
@handwerkerd: that was definitely my intuition, as well! We've done our best to convert as much of the codebase to `samples x echos x time` format for now, with two notable exceptions being (1) during spatial clustering, and (2) locating high-frequency spatial artifacts. I think this is the intent moving forward!

Re zcat files: I believe @tsalo's primary issue with them is that reshaping them into a usable form requires knowing the number of echos that are stacked atop one another. If we're consistently passing data files around in an attempt to make the functions in the codebase as modular as possible (i.e., not *requiring* `samples x echos x time` data, but accepting lists of filenames, too, as initially suggested), then accepting zcat files would also require passing through info on the number of echos. While it's not a lot of work to do that, I think the goal is to try and make these functions as re-usable as possible (hence, Taylor's recommendation to potentially move these utilities to their own module); abstracting away from the zcat redundancy would help in that regard. Nevertheless, I imagine that `tedana` will retain functionality for accepting zcat files for a while, at least.

@tsalo: :+1: I like it! One thing that would be nice in the `unmask` function is to accept both a reference image (as in `nilearn.masking.unmask`) **and** a mask array. Oftentimes, we have a `S x E x T` data array that is masked (by a boolean `S` array) to an `M x E x T` array, subjected to some computation, and then we want to convert the resultant data array directly to an `img_like` object. Providing `unmask(data, ref_img, mask=mask)` to combine the zero-padding and reshaping in one step would be great! Currently, that functionality exists as `tedana.utils.unmask` and `tedana.utlis.new_nii_like`, but could be easily combined to great success. I think that's my only comment/request on your proposed structure&mdash;indeed, I think a lot of the proposed functionality may already exist in `tedana` and could just use some tweaking and light refactoring! If you want to take a whack at it I'd be happy to review!

**Comment by tsalo** [comment]
@rmarkello Do you know if `nibabel`'s `GiftiImage` can support 3D (i.e., `S x E x T`) data? I tried playing around with it with no success, but you're more familiar with `nibabel` and especially its gifti tools. In order to store unmasked data in `img_like` objects (and only jump to arrays after masking), we'd need to be able to keep the full multi-echo timeseries for surface data in images.

**Comment by rmarkello** [comment]
Hey! Apologies for going AWOL on this... I think that it would be great to simply work with `M x E x T` data&mdash;I can't think of anywhere in the codebase where the full `S x E x T` is necessary, but I'd want to check to confirm before making the move. I *do* like the idea of everything being img_like, though! That would make interfaces a lot nicer.

As for `GiftiImage`: traditionally (or at least, for all the gifti files I've worked with), the data are stored in the `darrays` attribute, which is a list of `GiftiDataArray` objects, one per timepoint. Each `GiftiDataArray` has its own `darray` attribute, which contains all the samples (vertices) for the data; however, there isn't technically a restriction on the shape of an array that can be put in a `GiftiDataArray.darray`, so we could just shove a `samples x echos` array into it... Do you think that would work? We'd have to write our own `apply_mask` and `unmask` function for working with gifti data, but that should be relatively straightforward!

**Comment by tsalo** [comment]
@rmarkello It looks like there's no problem with storing multi-echo data to `GiftiImage` objects, as you suspected. I don't know anything about L/R giftis though. 

I've opened a WIP PR, #70, with a rough draft of a new version of `load_data` (`load_data2`) that needs to be merged with the updated version of `load_data` currently in master. I'm also working on `apply_mask` and `unmask` functions that will work with multi-echo masks and gifti/nifti data. I haven't fully tested those yet, but I'll be curious to know what everyone thinks of the approach.

**Comment by jbteves** [comment]
Update: currently issues #249 and #250 are addressing modularization for smaller pieces. Should we decide which sections should be modularized and close this large issue in favor of many smaller ones @emdupre @tsalo ?

**Comment by tsalo** [comment]
Sounds good to me.
