### ISSUE TITLE
Agenda for 2019-12-20T10:00EST Call

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#507]
### Summary
We should make an agenda for the upcoming developer call. 
[Get your local time here](https://arewemeetingyet.com/New%20York/2019-12-20/10:00/Tedana%20Developer%20Call%20December%202019)

Zoom link will be in the agenda (same as usual)

### Additional Detail
We typically remind people about meetings in Gitter. However, as we're trying to centralize communications onto GitHub, it seems that we should try to keep each meeting in its own issue for easy reference. Please comment below with topics you would like to make it onto the agenda. 

Topics
- OHBM
- New Release
- Summer Internships
- 2020 Meeting Times

**Comment by jbteves** [comment]
Key issues that I think should go onto it:
- New Release
- Governance

The reasons I think we should discuss Governance:

1. We didn't get to at the hackathon.
1. We are a large enough group now that it merits some discussion to keep things organized and to make sure everyone is on the same page.
1. The end of the year is a good time to reflect on what should be done in the coming one.


HOWEVER, I think we should only discuss Governance if the following people can make it: @emdupre @KirstieJane @tsalo @handwerkerd as the most "senior" developers in the group.

**Comment by emdupre** [comment]
I'd like to delay the governance discussion until the new year, since there's quite a lot of activity with OHBM deadlines and I want to make sure we don't conflate the pressure of those deadlines to add additional pressure here. It will also give me some time to draft a new roadmap, etc.

Personally I'd like to make sure that everyone is on the same page re OHBM submissions, and check in on the status of the projects started at the hackathon !

**Comment by jbteves** [comment]
Do we want to do that in January then? Sorry, I'm not submitting to OHBM and I keep forgetting everybody is getting stressed over that, my mistake.

**Comment by emdupre** [comment]
> Do we want to do that in January then? 

I don't think we'll _settle_ anything on that call, but it'd be great to discuss it then, yes !

**Comment by handwerkerd** [comment]
I agree with @emdupre on status of projects since hackathon. It would be good to get  BRIEF summaries of key active PRs and Issues. I don't want to dig into details, but there are so many moving parts right now that it would probably be good to verbally make sure everyone on the call knows the general status of the various efforts.

As for governance, I'm fine postponing to January... or even making it a stand-alone meeting.

One other topic that I was going to bring up post-OHBM. The internal NIH mechanism for funding the tedana hackathon that I applied to last year (and wasn't funded) is due January 17th. I have some thoughts on how to apply this year. It would be good to start that discussion.

**Comment by jbteves** [comment]
@emdupre @handwerkerd : I agree we should not *settle* anything in January. That is way too fast to make decisions. 

I agree that summaries of each project thrust would be good.

I disagree with making a separate governance meeting on two grounds: (1) scheduling is hard and it's good to avoid meeting proliferation, (2) we're not making final decisions anyway.

@handwerkerd could you actually make an issue for that funding mechanism outlining what we as a group can do to apply for this funding?

**Comment by KirstieJane** [comment]
This all sounds great to me - thank you for coordinating us @jbteves!!

Can we also add a GSOC student application to this month's agenda? The deadline is Dec 31, and I'd quite like to put a version of the same work that @monicayao worked on this year as there's still lots of code to test 😸

**Comment by KirstieJane** [comment]
The zoom link will be available (I'll be at the meeting 😄)

And can we also have an agenda item for checking that these times still work for the majority of attendees? It would be a good time to adjust for 2020 if we need to.

**Comment by handwerkerd** [comment]
I'm fine not making a separate governance meeting. In that case, perhaps we can attempt to block off a fixed amount of time in January (perhaps also a 5 min block in December just to make sure this discussion does get started).

For the intra-NIH funding for another hackathon, I have some thoughts on it & would rather briefly brainstorm on Friday rather than open an issue.

In addition to GSOC, NIH has [paid](https://www.training.nih.gov/student_irta_stipend_levels) Summer Internships for high school through grad students. If you know someone who might want to spend a few months at NIH specifically to work on multi-echo analysis/software/etc, please contact me. The full program info is at: https://www.training.nih.gov/programs/sip

**Comment by jbteves** [comment]
I think this is all good. Perhaps we can bring up the idea of summer internships generally and briefly brainstorm what kind of work summer interns of different skill levels could do, does that work for you @KirstieJane and @handwerkerd ?

**Comment by KirstieJane** [comment]
Yep - perfect!

**Comment by jbteves** [comment]
Thanks @handwerkerd

**Comment by jbteves** [comment]
Meeting was adjourned; closing
