### ISSUE TITLE
Ugly browser tab text on RTD

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#511]
### Summary

I'm not sure if this was already known to others, but I just noticed that the title text in the browser tab of the [the ReadTheDocs site](https://tedana.readthedocs.io/en/latest/index.html) currently includes 'tedana 0.0.8+88.g5e6918a.dirty documentation' 

### Additional Detail

I'm not sure which PR it was in, but I suspect this is related to the RTD change that places a banner if the generated RTD page is from a non-master branch.

### Next Steps

- If there is an obvious fix, hopefully someone can do it.
- If there is not an obvious fix, I doubt anyone will lose sleep over this.

**Comment by emdupre** [comment]
It's because we're building RTD from latest, rather than stable ! It's just giving you the name of the commit :smile_cat:

To fix, all we need to do is decide to build from stable. I think the discussion was to start doing that after the next release. @jbteves @KirstieJane , do you have a similar recollection ?

**Comment by jbteves** [comment]
I think the discussion was to switch over to do stable once we had fixed the PCA step, which will of course be the next release. Even if that's not what happened, I at this moment think that's the best idea.

**Comment by tsalo** [comment]
Done!
