### ISSUE TITLE
Consider switching readthedocs from "latest" to "stable"

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#567]
### Summary
We should consider switching the readthedocs page from rendering documentation from the "latest" version of tedana to the "stable" version of tedana (currently 0.0.9a). 

### Additional Detail
I think we should consider this in tandem with setting a regular release cycle, as these issues would play into each other. Please discuss below whether you agree with switching the readthedocs from "latest" to "stable" complete with your argument for which is more favorable. Current arguments in favor of switching include matching what users get with pip, current arguments in favor of staying include the idea that users should really pull the latest possible commit instead.

Credit to @tsalo for bringing this up and @handwerkerd for discussing in Gitter.

### Next Steps
Discuss and form concensus.

**Comment by handwerkerd** [comment]
I lean very slightly towards "latest" because I assume most users are still using that branch rather than the pip installed branch. Also, if we're updating the general multi-echo user guide, it would be nice to have those edits appear as soon as they've are on the latest branch.

That said, I don't have a particularly strong opinion, and if we do have a more frequent & regular release cycle, then the differences between the two will be minimal.

Also, the dropdown menu to switch between latest and stable is at the bottom-left of the RTD page and would likely be ignored by most readers. One potential middle ground would be to find a way to draw more attention to that option.

**Comment by tsalo** [comment]
BTW this is related to #511, starting with https://github.com/ME-ICA/tedana/issues/511#issuecomment-568080831.

**Comment by jbteves** [comment]
Thanks for the reminder @tsalo ! Yes, that was the original plan. So let's consider switching it at the next release, maybe?

**Comment by tsalo** [comment]
Agreed. I've pinned this to 0.0.9.
