### ISSUE TITLE
Topics for May 2020 Developers Call

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#569]
### Summary
The tedana developer's call is scheduled for this Friday, May 15th, at 10AM EST.
Check the time [here](https://arewemeetingyet.com/New%20York/2020-05-15/10:00/Tedana%20May%202020%20Dev%20Call)
The current [agenda](https://docs.google.com/document/d/1m1noOAUHmI7IxOc0u0ZW4DHsWzimeeawcwDNwok5OJQ/edit?usp=sharing)

Please comment below to indicate items you'd like to see added to the agenda.

**Comment by handwerkerd** [comment]
I've cleaned up and updated the current agenda doc. Read in advance, if you get a chance to re-prioritize items in the agenda, or think of responses.

I do want to politely nudge @KirstieJane about two agenda items:
1. If you get a chance, look up some of your past work on governance documents so that it can better inform #539 +
2. Open issue on how to track & credit author contributions & update Zenodo.

We also talked about submitting presentations to the Open Science room & about potential tedana-adjacent projects for the OHBM hackathon. @smoia was potentially taking the lead on the Open Science room, but I think proposal deadline 1 is this Friday. For the hackathon, anyone willing to take the lead on a project proposal/organization? More details on both of these are in the agenda.

...and just so I'm not leaving myself out of polite nudging, @handwerkerd needs to get to work on modularization. What's taking you so long?

**Comment by smoia** [comment]
Answering to @handwerkerd polite nudging - sorry for the delay in this!
I started crafting a proposal for an emergent session [here](https://docs.google.com/document/d/1gE8LW8Pg9h6jNT1KfapWuuxNzO3VUHjvkJgeFz_jRwE/edit?usp=sharing).

If it's possible we can submit today for the first round - as long as it's the 15th of May somewhere in the world, apparently. However, apparently there is no deadline for the [emergent sessions](https://ohbm.github.io/osr2020/formats/), since it's possible to propose them at the meeting itself.

Before you think that my intention is to subvert or diminish what the tedana community has been doing until now, I'd like to clarify the first aim of the proposal.
It would be incredibly nice to see a flourishing interdisciplinar community of ME users, eventually to getting to something similar to the Imaging Cerebral Physiology community. tedana could be a great hq for that, but first we need to understand if there is any action that should be taken to facilitate more users to join, and if it's actually in the interest of the current tedana to do so - meaning that the development of this repository might not be the main focus any more. I can further explain in the call today, if you want.
