### ISSUE TITLE
On the different normalization approaches in tedana

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/tedana#655]
This issue is just a summary of the discussion happening in #636 

As I was working on the integration test for the maPCA package, I noticed that for some reason we are not normalizing the data as a first step in mapca.py. We are normalizing further down the maPCA pipeline though (as we should be doing). This reminded me that during the DC hackathon we decided to use `data` instead of `data_z` as the maPCA input.

So, I thought a comparison of the different normalization approaches would be nice, i.e. comparing the z-scoring in the temporal domain like the one tedana applies for `data_z`, the sklearn `StandardScaler` we use in maPCA and the normalization GIFT applies.

Basically, the sklearn approach we introduced with maPCA back in 2019 is very much equivalent to the approach in GIFT. These two approaches normalize both in the time and space dimensions, but especially in the spatial domain with `np.mean(data, axis=0) = 1e-17` and `np.std(data, axis=0) = 1`, while `np.mean(data, axis=1) = 1e-2` and `np.std(data, axis=1)=0.98`. However, the opposite happens when calculating the mean and std on the data normalized with [pca.py lines 186-187](https://github.com/ME-ICA/tedana/blob/45e5ad7ab23f89dad091c3f0b6c7cc61062a0acc/tedana/decomposition/pca.py#L186-187) in tedana: `np.mean(data, axis=0)=1e-3` and `np.std(data, axis=0) = 0.99`, while `np.mean(data, axis=0)=1e-17` and `np.std(data, axis=0) = 1`.

I personally do not think these differences should make any difference in computing maPCA.

As of right now, the new maPCA package provides the option to set `normalize=False`, which means tedana could input `data_z` into maPCA. However, as we're especially interested in z-scoring in time, I'd incorporate [pca.py lines 186-187](https://github.com/ME-ICA/tedana/blob/45e5ad7ab23f89dad091c3f0b6c7cc61062a0acc/tedana/decomposition/pca.py#L186-187)  into maPCA and use those instead of using sklearn's `StandardScaler`.

This little study has come a bit later than we all would've hoped, but I believe it is very important we know what we have in hand. Hopefully, this will make our stand on normalization clearer for the future.

**Comment by notZaki** [comment]
Were these results on an fmri data or simulated data?

I've observed that `StandardScaler` only normalizes along `axis = 0` and the choice of using `scaler(data)` vs `scalar(data.T).T` substantially changes the number of components estimated by maPCA when using fmri data.

**Comment by eurunuela** [comment]
I did it on random data. I've just checked on the 5 echo dataset and your transposing trick makes sense.

**Comment by notZaki** [comment]
I'll add some of my observations.

For context, the maPCA does normalization in two parts of the code: (1) initially when estimating eigen values, and (2) in an inner loop. The table below describes the type of normalization used in (i) the current master branch of tedana, (ii) GIFT, and (iii) PR636

| Method | Initial Normalization | Inner Normalization |  
|----------|--------|-------|
| Master  | None  | Voxel |
| GIFT      | Voxel  | Voxel |  
| PR636  | Time    | Time  | 

If we apply maPCA to 88 subjects from the [multi-echo cambridge dataset](https://openneuro.org/datasets/ds000258/versions/1.0.0) then the number of estimated components is: 

![numcomp](https://user-images.githubusercontent.com/9019681/105232536-23ab8a80-5b2e-11eb-9ab9-cda4ef662d61.png)

For simplicity, I didn't show the master branch in the above figure. It tends to be similar to GIFT. The figure below plots the difference between GIFT-vs-master and PR636-vs-master.

![diffcomp](https://user-images.githubusercontent.com/9019681/105234385-ce24ad00-5b30-11eb-9a10-2e62f964e274.png)

---

A lower number of components is estimated by maPCA when normalization is performed in time domain instead of the space domain. Not sure if this is good or not, but it does result in faster ICA.

**Comment by eurunuela** [comment]
Thank you @notZaki !

I think we should stick to what GIFT does for the moment (that was our intention when we incorporated maPCA into tedana) and further study how these differences affect the ICA step in tedana. 

So, first, I would make sure #636 fixes the missing normalization at the very beginning of maPCA to make sure the next tedana release is applying both normalization steps.

Then, I would select a couple of the subjects in the multi-echo Cambridge dataset (for instance, one with few components and one with many) and see if the results make more sense when we normalize in the temporal domain.

**Comment by notZaki** [comment]
I think we would need to make all steps---i.e. maPCA, PCA, and ICA---use the same normalization approach to have a meaningful comparison. Right now we have:

- maPCA normalizes either along time or voxels
  + GIFT normalizes along voxels
  + PR636 and maPCA are moving towards normalizing along time
- PCA normalizes along both dimensions at different stages
  + `pca.fit` normalizes along voxels
  + pca's output is then z-scored along time by tedana 
- ICA: assumes normalization is along voxels

Is the ICA supposed to be spatial or temporal? If it is spatial, then perhaps it makes more sense to normalize along voxels in all the steps and remove any temporal normalization.  

---

As a first step, I wanted to test a simple scenario where ICA is preformed without PCA, so I processed 88 subjects in the [multi-echo cambridge dataset](https://openneuro.org/datasets/ds000258/versions/1.0.0) using two approaches: (i) using the current code which uses PCA for dimensionality reduction, (ii) a modification where PCA is not used to reduce the data prior to ICA---in other words, `decomposition/tedpca` returns `data` instead of `kept_data`.
Both approaches still use maPCA to estimate the total number of components, and this value is used in the ICA decomposition.
ICA was used with `whiten = True`.

Looking at the results, more components were accepted when PCA is skipped (fig below), but that isn't necessarily a good or bad thing.

![numcomp_withoutPCA](https://user-images.githubusercontent.com/9019681/105815230-3aac0b80-5f78-11eb-8fec-e038d19e4da0.png)

What I found more interesting is that if I repeated the same process but changed the python version, then the approach without PCA remains consistent while the approach using PCA does not. So from a reproducibility point-of-view, PCA is doing more harm than good. I'll try playing with the normalization steps in PCA to see if it that improves things.

![diffcomp_withoutPCA](https://user-images.githubusercontent.com/9019681/105816330-c7a39480-5f79-11eb-93df-f039be4f9361.png)

Here's the figures for the first subject in the dataset, if anyone's interested in digging through them:
[04570_withPCA.zip](https://github.com/ME-ICA/tedana/files/5872028/04570_withPCA.zip)
[04570_withoutPCA.zip](https://github.com/ME-ICA/tedana/files/5872029/04570_withoutPCA.zip)

**Comment by emdupre** [comment]
Commented [elsewhere](https://github.com/ME-ICA/tedana/issues/653#issuecomment-768597598), but to echo here: 

We're interested in a spatial ICA, as this is what ME-ICA was originally implemented with. That being said, the PCA we're implementing here is largely for an initial dimensionality reduction to hopefully find more "meaningful" components with ICA. In the original implementation, the PCA had its own decision tree which underscored this fact (we still retain that option, [here](https://github.com/ME-ICA/tedana/blob/f422a2fb002d6a849661b3cd6e8ed6d6746dd013/tedana/selection/tedpca.py#L18)). So, seeing more components selected without the PCA certainly makes sense !

The fact that we're not seeing reproducible behaviour across python versions suggests (to me) that one of our dependencies has introduced new behavior between 3.7 and 3.8 that impacts the PCA performance in sub-selecting components. If instead the normalization stabilizes this, then it's likely a compounding numerical difference :grimacing:  Which can be hard to isolate.

I hope that by being principled about the normalization, we can ensure reasonable behavior, here !

**Comment by notZaki** [comment]
> The fact that we're not seeing reproducible behaviour across python versions suggests (to me) that one of our dependencies has introduced new behavior between 3.7 and 3.8 that impacts the PCA performance in sub-selecting components. If instead the normalization stabilizes this, then it's likely a compounding numerical difference 😬 Which can be hard to isolate.

That's a good suggestion. 
I did a quick scan through the dependencies, and what stood out is that my python 3.7 environment was using openBLAS while the py3.8 environment was using MKL. That probably explains why the results were so different. 

I do still think that there are ways to reduce some of this variability by changing how the data is normalized.
I re-processed the cambridge dataset, this time with PCA but changing the normalization that happens between the PCA and ICA steps, i.e.:
https://github.com/ME-ICA/tedana/blob/ca7e14521c1b632f46055502bcf19b1d4f4db8f0/tedana/decomposition/pca.py#L284-L285

Three versions were attempted:

1. Temporal normalization: This is just the current master
2. Spatial normalization: The normalization in the above code is changed from `axis = 1` to `axis = 0`
3. Temporal normalization with whitening: This uses the same temporal normalization as the current master, but with `whiten = True` in the ICA function. I believe the whitening step in ICA involves spatially normalizing the data to have a mean of zero without any additional scaling. 

Based on the figure below, a majority of the variability is eliminated if spatial normalization is used---either explicitly using method 2 or through ICA's whitening option in method 3. 

![diffcomp_withNormalization](https://user-images.githubusercontent.com/9019681/106407172-006fbd80-6401-11eb-87f6-eb9863dd60b8.png)

**Comment by eurunuela** [comment]
Thank you @notZaki . I guess we should go back to the papers and see if we find out why GIFT performs normalization along the spatial dimension. 

It also makes sense to me that the spatial normalization is more stable as you would probably expect to have less variance in the time domain; i.e. if we fix volumes to mean 0 and std 1 the number of points that provide variance is much smaller than if we normalized in time (`n_voxels >>> n_frames`).

**Comment by emdupre** [comment]
Should we close this now that #636 is merged and #653 is still open ?
