### ISSUE TITLE
Reorganize RTD tree

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#677]
### Summary
I think our current sidebar/organization is a little suboptimal, so I'd like to restructure it a bit. I've opened this issue so we could discuss my idea.

### Additional Detail

Here's my proposal (happy to amend):

```
- Installation  # add instructions to install from GitHub source
- About multi-echo fMRI  # new page
    - What is multi-echo fMRI?
        - Current sections on physics, why to use, considerations, and costs and benefits.
    - Acquiring multi-echo fMRI
        - Current sections on available sequences, parameter recommendations, and common parameters
    - Processing multi-echo fMRI  # moved from "Using tedana" page
    - General resources  # renamed from "Resources"
- Using tedana from the command line  # renamed from "Using tedana"
    - Running the tedana workflow  # renamed from "Running tedana"
    - Running the t2smap workflow  # renamed from "Running t2smap"
- tedana's denoising approach  # renamed from "The tedana pipeline"
- Outputs of tedana
    - tedana derivatives
    - Component tables
    - Citable workflow summaries
    - ICA Components Report  # moved from its own page
- FAQ  # drop "tedana" and "multi-echo fMRI" subsections and add prefixes (e.g., "[tedana]") to questions
- Support and communication
- What's New  # see #676 
- Contributing to tedana
    - Developer guidelines  # moved from its own page
    - Governance  # moved from its own page
- The tedana roadmap
    - Scope of tedana  # moved from contributing page
- API
```

**Comment by emdupre** [comment]
Pinging in @dowdlelt and @mvaziri since they led the last documentation sprint :) 

This looks good to me @tsalo , thanks for proposing it ! My only immediate thought : 

> - Using tedana from the command line  # renamed from "Using tedana"

The phrasing makes me think that there's an alternative, but since we explicitly rule out a GUI I'm not sure what that would be...
Is just "Using tedana" too short, you think ?

**Comment by tsalo** [comment]
People can use tedana with the Python functions. I generally go that way when I'm testing things/debugging.

**Comment by dowdlelt** [comment]
I like the change from tedana pipeline - because once we get another method, is as easy as making that "approaches" and adding subsections. I suppose one concern is that tedana outputs may become dependent on the denoising approach used - but that is bridge in the far distance, and I don't think we need to change things now. 

Moving processing out is good - better to break the connection between MEICA handling preprocessing and tedana not helping with that. 

I also think installing from github source is useful, per our discussions of release delays - this is how you can be sure to be using most recent versions and helps with answering questions. Our response can now be, see here to install the most recent version, rather than, we will release that fix "soon" (TM).

**Comment by emdupre** [comment]
> People can use tedana with the Python functions. I generally go that way when I'm testing things/debugging.

Ah I see ! Sorry, I think I'm thinking in a very user-focused mindset when I look at this, and I don't know that everyone will distinguish between "command line" and "python prompt in terminal." They're different, of course, but I don't know that we should expect everyone to think of that. Not a strong feeling, though ! 

I definitely agree that the API currently comes off as a bit of an after-thought, which we should fix !
