### ISSUE TITLE
Add fmrwhy to multi-echo resources

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#683]
### Summary

Recently, @jsheunis introduced fmrwhy (https://fmrwhy.readthedocs.io/), a MATLAB package for processing multi-echo data. It would be great to include this in our documentation as a resource for the multi-echo community !

### Additional Detail

I think it would need to be added [here](https://tedana.readthedocs.io/en/stable/multi-echo.html#resources) under **Multi-echo processing software**, but pending #677 the exact text area could be updated.

### Next Steps

Open a PR to add this in :smile_cat:

**Comment by zswang-brainimaging** [comment]
@emdupre  Thank you for this information!  Will see if something can be combined with your toolbox.

**Comment by emdupre** [comment]
> @emdupre Thank you for this information! Will see if something can be combined with your toolbox.

That's great, @zswang-brainimaging ! Glad to hear that it's useful to you. If you're primarily working in MATLAB, `fmrwhy` seems like an especially important resource.

It's always challenging to integrate MATLAB and Python environments, but if you find a path using both `fmrwhy` and `tedana` that's useful for you, definitely let us know !

**Comment by handwerkerd** [comment]
I'm trying to go through old issues to see what we can address. I can definitely add fmrwhy to the docs, but it looks like it hasn't had any commits in over a year. Since we regularly get questions on using multi-echo data with SPM it's very worth adding, but I want an accurate description.
@jsheunis, Should the descriptive text me something like:
"fmrwhy runs BIDS-compatible fMRI analysis with SPM12 and supports multi-echo data. It is no longer being actively maintained"

**Comment by jsheunis** [comment]
@handwerkerd thanks for the message, that is accurate yes. I'll update the repo with a similar note.
