### ISSUE TITLE
Kappa and Rho are only calculated from "perfect" voxels

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#713]
`F_R2` and `F_S0` should only have non-zero values in voxels where `adaptive_mask == j_echo`, while `F_R2_maps` and `F_S0_maps` should be filled in with values at all voxels where `adaptive_mask >= 3` over the `j_echo` loop:
https://github.com/ME-ICA/tedana/blob/0f4d54c375ffd2a4b96ebd6a662269ea3b92d691/tedana/metrics/kundu_fit.py#L185-L186

However, we _calculate_ kappa and rho from `F_R2`, not `F_R2_maps[:, i_comp]`, which means that kappa and rho are probably only calculated from the F-statistics for voxels with good data in all echoes, along with a bunch of zeros:
https://github.com/ME-ICA/tedana/blob/0f4d54c375ffd2a4b96ebd6a662269ea3b92d691/tedana/metrics/kundu_fit.py#L202

EDIT: The good news is that this bug is also not present in #591, since we pass the 2D `F_T2_maps` and `F_S0_maps` instead of the reduced 1D `F_T2` and `F_S0`.

_Originally posted by @tsalo in https://github.com/ME-ICA/tedana/issues/710#issuecomment-812191727_

**Comment by jbteves** [comment]
Oh, good idea opening this separately, thanks @tsalo !
Just FYI this is a surprisingly small difference for the data I've tested; typically one part in 1e-14 to 1e-15, fortunately, for three-echo data. It could be much worse for 5-echo, however. I'm inclined to fix it by merging in modularization rather than to fix it in `main`, but if you disagree I'll open up another PR to fix this one, too.

**Comment by tsalo** [comment]
TBH, I'm surprised that it would make _any_ difference for three-echo data, since we require three good echoes to calculate these metrics.

**Comment by jbteves** [comment]
Hm, I misunderstood the logic. Perhaps we have some other small bug that modularization fixes.
