### ISSUE TITLE
Add minimally-preprocessed Cambridge dataset to datasets module

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#779]
### Summary

One dataset we may want to include in the new `datasets` module is [Multi-echo Cambridge](https://openneuro.org/datasets/ds000258).

### Additional Detail

~~I have this dataset preprocessed with fMRIPrep and can handle the upload.~~ This dataset was preprocessed by @notZaki and is on the OSF.

### Next Steps

1. Determine preferred location for data.
2. Add data to location.
3. Build manifest (not sure how this is done).
4. Add new dataset to `datasets` module.

**Comment by tsalo** [comment]
Kinda forgot that this was part of #720... 🤦 

Well at least having an issue about it will help with tracking things.

**Comment by tsalo** [comment]
@notZaki would it be possible for you to add the nifti files' sidecar files to the OSF repository? They would need to be manually produced, I think, using the original files' sidecars.

**Comment by tsalo** [comment]
Also, it looks like the downsampled files' headers were overwritten, as the headers now indicate a TR of 1.

**Comment by notZaki** [comment]
That's likely because the downsampling procedure uses `nilearn.masking.unmask` before resampling the data. I can reupload the downsampled images with the corrected TR---along with the sidecar files.

**Comment by tsalo** [comment]
@notZaki two questions:

1. Have you had a chance to fix the downsampled images' headers and add the sidecar files?
2. Would you be willing to write up how you generated the `manifest.json` file? I think it would be good to incorporate that into our documentation in #805 for future datasets we end up hosting on the OSF.

**Comment by notZaki** [comment]
@tsalo The downsampled images were fixed, but they haven't been re-uploaded to [the OSF repo](https://osf.io/9wcb8/).
I guess one thing I'm not sure is whether to have the downsampled images + sidecars be on their own with a flattened directory structure (as they are currently) or include them in the derivatives-like structure (where the transforms and original resolution data is currently).
Is one better than the other? (Does it even matter?)

I wrote a [package in julia](https://github.com/notZaki/OSF.jl) to upload to OSF because---as you noted---it's a pain to upload multiple files. The same package also generates the manifest file via the `osftree(repo_id)` function. I can write something with more details if there is interest. There is also [osfclient](https://github.com/osfclient/osfclient) which might have similar features, but it was very slow at uploading (issue 155 in their repo has some details with a potential fix in a PR).

**Comment by tsalo** [comment]
>I guess one thing I'm not sure is whether to have the downsampled images + sidecars be on their own with a flattened directory structure (as they are currently) or include them in the derivatives-like structure (where the transforms and original resolution data is currently).

I think they'd work best within the main derivatives-like structure. Just with the `res-5mm` keyword.

>I wrote a package in julia to upload to OSF because---as you noted---it's a pain to upload multiple files. The same package also generates the manifest file via the osftree(repo_id) function.

Awesome!

>I can write something with more details if there is interest.

That would be great. Perhaps a section in our developers guide on adding new datasets?
