### ISSUE TITLE
Undocumented sensitivity to bracket type in API

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#801]
### Summary
I was trying to figure out why I was getting different results running tedana with the command line interface (CLI) vs calling commands with the API in python. It turns out I was using parentheses around the list of data file names instead of square brackets. This gave no warnings, the program ran, but the results were wrong.

### Additional Detail
I tested this with the data set we use for the OHBM demos: `curl -L -o five_echo_NIH.tar.xz https://osf.io/ea5v3/download`
As far as I can tell, running the following gives the same t2s maps as the CLI
```
workflows.tedana_workflow(
    [
        "p06.SBJ01_S09_Task11_e1.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e2.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e3.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e4.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e5.sm.nii.gz",
    ],
    (15.4, 29.7, 44.0, 58.3, 72.6),
    verbose=True,
    out_dir="tmp",
)

```
If parentheses are used instead, the t2s values are implausibly large
```
workflows.tedana_workflow(
    (
        "p06.SBJ01_S09_Task11_e1.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e2.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e3.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e4.sm.nii.gz",
        "p06.SBJ01_S09_Task11_e5.sm.nii.gz",
    ),
    (15.4, 29.7, 44.0, 58.3, 72.6),
    verbose=True,
    out_dir="tmp",
)
```

### Next Steps

- Confirm others see the same thing & that I'm not just doing something extra weird
- Either adjust the API to properly parse parentheses around file names or throw some sort of error up when they are used.

**Comment by tsalo** [comment]
At a glance, I think it boils down to this part of `load_data`:

https://github.com/ME-ICA/tedana/blob/bb573840da9176374ee8f4e9cb50e15ff7f097e1/tedana/io.py#L584-L595

We explicitly check if the input is a list and load the data in one way if it is, but load it in another way if it isn't. If given a tuple (parens) of files, it looks like nilearn's `check_niimg` function is called, which concatenates all of the files in the fourth dimension, and then the loading function assumes the input is a z-concatenated file and splits up the data based on that!

As a test, I took eight echoes of data with the shape `(64, 70, 34, 220)` (something Logan shared):

```python
from tedana.io import load_data

files_tuple = [
 'sub-pilot_task-rest_run-2_echo-1_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-2_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-3_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-4_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-5_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-6_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-7_bold.nii.gz',
 'sub-pilot_task-rest_run-2_echo-8_bold.nii.gz',
]
files_tuple = tuple(files_list)

# btw n_echos is documented as optional, but isn't treated as such
data_list, _ = load_data(files_list, n_echos=8)
data_tuple, _ = load_data(files_tuple, n_echos=8)

print(data_list.shape)
# (152320, 8, 220)

print(data_tuple.shape)
# (17920, 8, 1870)
```

Technically, it's documented since we specify that `data` and `tes` must be lists (square brackets) in the docstring, but it's not sufficient when feeding in a tuple will cause problems without raising any exceptions.

**Comment by tsalo** [comment]
I think we should revisit `load_data` (`n_echos` should be optional) and, at minimum, just convert the data parameter to a list.

**Comment by jbteves** [comment]
Ah, thanks for checking that out @tsalo. That makes a lot of sense. I would be in favor of coercing inputs into lists.
