### ISSUE TITLE
[JOSS review] Documentation suggestions

### ISSUE THREAD

**Issue by stebo85** [ME-ICA/tedana#804]
The Documentation of the project is very comprehensive and includes all information one could hope for. I only have small suggestions for further potential improvement if the authors think this is feasible and relevant:

1) I was wondering if it would be possible to add examples in the section "Using tedana" including a small dataset that users could use to run tedana or t2smap on before applying it to their own data. Ideally the most important outputs of these examples could be briefly explained and then linked to the full "Outputs of tedana" section.

2) The duecredit warning is described in the FAQ, but for a naive user it looks like something went wrong. Would it make sense to link to this explanation from the Installation section?

https://github.com/openjournals/joss-reviews/issues/3669

**Comment by emdupre** [comment]
Thank you for your review, @stebo85 !

We've added a note about `duecredit` as an optional dependency to the installation section in https://github.com/ME-ICA/tedana/commit/cd3a41b77fa46f1c6b960a79707c3f6a1c190a63, [diff visible here](https://github.com/ME-ICA/tedana/commit/cd3a41b77fa46f1c6b960a79707c3f6a1c190a63#diff-d9b149498982c0663c3b7170398773361ed5678f1a627e9c2fd8d2c955c563db).

Otherwise, I definitely agree that having more interactive examples in the documentation would be useful -- this is also something @martinagvilas brought up as part of her review in #798. I'm not sure, though, if this is immediately feasible, for the reasons outlined there.

Please let me know if this (and the linked commit !) addresses your concerns, here !

**Comment by stebo85** [comment]
Dear @emdupre,

Thank you for adding this - this is now much clearer.

I still think that better examples would be important, but if you believe that it's not feasible in a realistic timeframe than I will not be in your way.

Kind regards
Steffen
