### ISSUE TITLE
March Developers' call. Thursday, 3/17/2022

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#857]
Our next dev call is scheduled for Thursday, 3/17 at 4:00 PM CET / 10:00 AM EDT / 2:00PM UTC / 7:00 AM PST
[Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+March+2022&iso=20220317T10&p1=263&ah=1)
If you'd attend, but our regularly time is a problem let us know!

https://nih.zoomgov.com/j/1611947107?pwd=aHVOQTBMYWVkNmE0cnR4d3ZkYmd5UT09 
Meeting ID: 161 194 7107
Passcode: 038728

[Meeting agenda](https://docs.google.com/document/d/10PF071ApPBmQizBqL5c9ypA3-gl6sDoB-ws7Yi2LeYo/edit?usp=sharing).
NOTE: The agenda is still mostly a copy from February. I'll working on updating it on Wednesday

If there are things you know you want to discuss add them either here or in the agenda.

**Comment by emdupre** [comment]
Just confirming that I _won't_ be at this meeting tomorrow since it's 7a local time :disappointed:  I'll catch up from the minutes and try to coordinate a discussion about shifting the time for future meetings (so there's a bit more heads up).

Since @eurunuela will be on the East Coast starting next month (?!) -- at least for a few months -- maybe once he's settled we could aim to re-schedule the slot / reach out to other folks for their availabilities.

**Comment by eurunuela** [comment]
> Since @eurunuela will be on the East Coast starting next month (?!) -- at least for a few months -- maybe once he's settled we could aim to re-schedule the slot / reach out to other folks for their availabilities.

I'll be on the East Coast from mid May to mid August. Feel free to reschedule April's meeting too, it will probably be on our Eastern break.
