### ISSUE TITLE
Design and write results viewing code

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#86]
@emdupre mentioned this in #84, but I think it's worth it's own issue. We all want a way to do an efficient visual review of multi-echo denoising results. One version of this review is at https://github.com/handwerkerd/Meica_Report That may be useful for thinking through features, but, given newer MRI data visualization modules, it might be easier to start the code from scratch.

I don't think actually working on this is anyone's highest priority, but this issue thread will be a good place to compile/discuss design features. Here's my starting list based on the earlier Meica_Report:
* Plots of the sorted kappa & rho values as well as a scatter plot of kappa vs rho with component variance information and coding on whether each component was accepted or rejected
* A way to view all ICA components with their spatial maps, time series, and FFTs of time series.
* Ideally an interactive way to click on components in a scatter plot to quickly see the spatial maps & time series
* TSNR maps (also summary TSNR values)
* motion parameters
* Most of the information in comp_table.txt
* A way to merge resukts from multiple denoising runs into a single html page or spreadsheet for efficient comparisons across a study

* An efficient way to see the detailed provenance for why each component was accepted or rejected (Given the current direction of the code, we should include the link to the code version somewhere in the report & the precise command that was called to run all or part of the tedana pipeline)

**Comment by emdupre** [comment]
@chrisfilo has some code for plotting ICA components that might be worth thinking about here, too ! Plus the general framework for [MRIQC reports](http://mriqc.readthedocs.io/en/latest/reports.html).

**Comment by chrisfilo** [comment]
https://github.com/poldracklab/niworkflows/blob/a82096a18d3cbd2b8ca2d0345f5d98f1ce3094f1/niworkflows/viz/utils.py#L482

**Comment by tsalo** [comment]
The niworkflows MELODIC plot works pretty well for the MEPCA and MEICA components, although we need to convert files to the MELODIC format and write out the MEPCA components to a nifti file. I'm working on this in my [tables](https://github.com/tsalo/tedana/tree/tables) branch. It would be nice if we could abstract the core parts of `plot_melodic_components` to a `plot_components` function that would allow us to do the following:
1. Specify relevant files instead of relying on the MELODIC naming convention/folder structure
2. Use a custom dictionary of colors associated with different classifications (rather than just accepted --> green and rejected --> red), since MEICA at least has accepted, rejected, midk, and ignored

One weird thing is that the MEPCA component maps for the first ~100 components look weirdly dark (see below):
![image](https://user-images.githubusercontent.com/8228902/43687901-44129ee0-98ac-11e8-9638-145dac4e7663.png)

The MEICA ones look fine though (see below):
![image](https://user-images.githubusercontent.com/8228902/43687904-4f566976-98ac-11e8-908b-18adbb194863.png)

**Comment by handwerkerd** [comment]
I haven't used plot_melodic_components before, but those all look a bit weird to me. Are they glass brains or a single slice of each orientation? If we're trying to to a visual check for artifacts or issues, glass brains are probably not ideal. Particularly for checking multi-echo denoting, I've found that being able to look at the power spectrum of the time series can also be useful.
Thank you for pushing forward on this.

**Comment by chrisfilo** [comment]
Yes those are glass brains (maximum intensity projection of unthresholded maps). In my personal experience those are a good compromise for for situations when interactive exploration would be too time consuming. I prefer it better to showing cuts at one arbitrary coordinate. I would love to see an example of a component that cannot be clearly seen with glass brain. Having said that I admit it takes some getting used to.

BTW power spectrum is plotted for each component. The line plots on the right of each map: top) timeseries with axes in seconds; bottom) power spectrum with axes in Hz.

**Comment by handwerkerd** [comment]
I'm familiar with glass brains and I've had a couple decades to get used to them. I know they can be useful, but I find they're not ideal for visualizing artifacts or getting a sense of what's happening in a noisy component, which is what is relevant for this specific type of report. For example, in C2 and C8 of the visualization above, there's a ring at the top. It looks like the highest slice has more intensity than the other slices. Is that related to the nature of the maximum intensity projection? Is it a sinus-heavy component? Is it a slice-specific artifact or data reconstruction error? Is it brain activity that only appears in one or two axial slices? Is it caudal/rostral head motion? My guess is that it's either an artifact (something worth examining more) or sinus (an expected component), but I can't tell by just looking at the glass brain.

A agree that an interactive exploration is ideal, but not practical or fast. I've found that a display that includes ~5 slices in 2 orientations is much better for quickly scanning an output to look for weird things.

Thanks for pointing out the power spectra.

**Comment by chrisfilo** [comment]
I'm very interested in creation of compact static visualization of ICA components. It might help to see how the two approaches compare on the same components. @tsalo could you share the MEICA outputs you used so @handwerkerd could create corresponding figures (in a fully automated manner) with his method?

**Comment by tsalo** [comment]
Absolutely! I've just emailed both of you the files needed to generate the MELODIC component plots (before reorganization to match MELODIC structure).

**Comment by tsalo** [comment]
I've started working on a generalized version of `plot_melodic_components` in a fork of niworkflows [here](https://github.com/tsalo/niworkflows/blob/fb93adb86f3726bb800196e0be918ae890c51102/niworkflows/viz/utils.py#L488). Basically it just requires that all of the input files be provided as arguments, rather than being identified automatically based on MELODIC's output structure.

Before I raise an issue in `niworkflows` to ask if this would be useful, I thought I would bring it up here to see if we would all rather try requesting a change to `niworkflows` or write something ourselves. The resulting plots will be essentially the same as the ones above, except that we can use a custom set colors mapped to classifications beyond just accepted/rejected.

**Comment by tsalo** [comment]
Just a small update: I figured out why the PCA glass brains looked bad. It's actually because of a bug in `computefeats2` I found (see #178). This bug only affects the PCA component maps because the ICA mixing matrix is normalized, but the PCA one is not. Here is snapshot of the updated PCA plot:

<img width="756" alt="screen shot 2019-01-07 at 1 44 25 pm" src="https://user-images.githubusercontent.com/8228902/50786745-61f4ea80-1282-11e9-8d65-f2b780da2293.png">

**Comment by dowdlelt** [comment]
I created a pull request that produces very simple figures - perhaps not as pretty as the ones generated by @tsalo but I simply needed a way to view the components and understand what was going. Example figures for an accepted component:
![image](https://user-images.githubusercontent.com/15126366/51993024-10eca680-247c-11e9-8a49-aff85c75b944.png)



and a rejected component:
![image](https://user-images.githubusercontent.com/15126366/51993049-1ba73b80-247c-11e9-9d31-9f9692e36e53.png)

The code creates a figure per component and writes it to a ./figures folder within the tedana output location. It makes it quite easy to just roll through them with the system image viewer. I imagine this a simple way of looking at the outputs - no fancy bells or whistles - just quick. 

Thoughts? I am new to python so this is fairly hacked together, and it could use a color bar, L/R indicator among other things.

**Comment by dowdlelt** [comment]
Little addition, now produces a kappa vs rho plot:

![image](https://user-images.githubusercontent.com/15126366/52079966-ba0ecc00-2564-11e9-875c-81fa06d8f713.png)

Size is scaled by variance explained.

**Comment by dowdlelt** [comment]
Title of plots now includes kappa and rho values. Note that the color of the timeseries plot indicates accepted/rejected/ignored status as well with green, red, black respectively. More features to be added as time allows. 
![image](https://user-images.githubusercontent.com/15126366/54139130-4380ac00-43f7-11e9-9731-6fd6ac30096c.png)

**Comment by emdupre** [comment]
Now that #208 is merged I think we can close this and focus on #232 !
