### ISSUE TITLE
Additional fields in dataset_description.json identifying source files

### ISSUE THREAD

**Issue by andreifoldes** [ME-ICA/tedana#889]
### Summary
I think it would be very useful to have information about which source files Tedana was applied to in the dataset_description.json file perhaps for posterity. When conditions/sessions are relabeled it's easy to make mistakes/have uncertainty about what were the underlying files involved in a making the specific files.

**Comment by tsalo** [comment]
I agree that tracking the files is a good idea. However, the source files need to be set in the individual derivatives' sidecar files (which I don't believe we generate yet), while the dataset_description should have the source dataset's link. 

I'm currently working on tracking this information in another package, and it can be surprisingly difficult.

**Comment by andreifoldes** [comment]
Yes, I'm using 0.0.12 tedana and the only json files are the metrics/decomposition sidecars and the dataset_description.
So ideally this information would in be the output specific sidecars? If there would be a field storing the echo-wise preprocessed files and mask that would be great.

Since BIDS was mentioned: being able to pass "subject"/"session"/"task"/"space" fields to the tedana file names would also be cool - or maybe they could be extracted from the source filenames optionally?

**Comment by tsalo** [comment]
Incorporating those fields would require extracting them from the incoming filenames, which basically would mean writing a BIDS interface and expecting BIDS-compliant inputs. We decided a while back to not make tedana a BIDS App; however, there might be room for a BIDS App wrapper _around_ tedana that would do what you're talking about.

**Comment by handwerkerd** [comment]
@andreifoldes We just had our monthly developers' call and we discussed this issue. We are currently very close to merging a major change in the code: #756. As part of that change, there will be a new file `desc-tedana_registry.json` that lists identifiers and names for all outputted files. We weren't using that for input filename logging, but it won't be hard to add those file names, so that's our current plan.

Would that address this issue for you?

Also, the input file names are currently saved in the `tedana_[date/time].tsv` log that is created every time tedana is run. That log isn't as easily machine readable, but, if you need to figure out what happened on data that was already processed, this information has long been stored.

**Comment by andreifoldes** [comment]
Yes, that sounds wonderful!

Indeed! I forgot to look at the` tedana_[date/time].tsv`!
