### ISSUE TITLE
Save F_T2* and F_S0 maps

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#891]
### Summary

F statistics for fits of the multi-echo data to T2* and S0 models are calculated for use in various metric calculations. These used to be saved in meica, but, at some point we stopped saving them. @prantikk noted they can be useful outputs for quality checks and later steps so we should save them again.

**Comment by tsalo** [comment]
Aren't they written out with the verbose option?

**Comment by tsalo** [comment]
Sorry, it looks like verbose doesn't write these out.

To do that, we need to just do a couple of things:

First, we add something like

```python
if io_generator.verbose:
    io_generator.save_file(
        utils.unmask(metric_maps["map FT2"], mask),
        label + " component F-T2 img",
    )
    io_generator.save_file(
        utils.unmask(metric_maps["map FS0"], mask),
        label + " component F-S0 img",
    )
```

to this section:

https://github.com/ME-ICA/tedana/blob/c7924b502dd89dbd8f9c5fbc4581763c36b9dab8/tedana/metrics/collect.py#L153-L161

Second, we need to add the new image labels to the IO generator's config files.

I also think it would be a good idea to output the degrees of freedom maps for the F-statistics, since DOF varies across the brain based on the adaptive mask.

**Comment by handwerkerd** [comment]
I noticed this was sitting as a scrape note from a dev call a few months back and wanted to move it to an open issue. I think we previously realized it wasn't even being saved as verbose. I'm mixed on additionally saving the DOF map. We're already saving the adaptive mask and it should be directly calculable from that file.

**Comment by tsalo** [comment]
Yes, the DOF map should be the number of volumes minus the adaptive mask.

**Comment by prantikk** [comment]
In the old code, for the F_T2 F_S0 calcs,  the DOF is fixed to # of echoes
- did you make it dynamic against the # of valid echoes in a pixel for
tedana?

**Comment by tsalo** [comment]
Yup, exactly. We started doing that in #358.
