### ISSUE TITLE
Large variance components can be ignored

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#97]
I'm separating a comment in #77 into a distinct issue. I just ran tedana on a 5-echo data set. A component with ~3% of the normalized variance (~8% non-normalized variance) is ending up in the ignored bin. At least in the original version of the selcomps algorithm, the ignored components were solely defined by components with such low variance that they can be ignored and kept in the denoised data set with no addition classification steps. At least in that version, such a component would never be ignored. I'd seen something similar when processing another data set, but the variance was only around 1% so I didn't think to dig further then. This seems like a non-trivial issue that should be addressed before this version of the code gains wide use.

@prantikk, I know you have better things on your mind now than digging into this code, but I wanted to confirm with you that "ignored" should mean them same thing here as it meant in the earlier version & you agree that large variance components shouldn't ever end up classified as ignored.

**Comment by tsalo** [comment]
@handwerkerd @emdupre Given that we've committed to switching to v2.5 of the component selection algorithm for the foreseeable future, can we close this issue?

**Comment by jbteves** [comment]
@handwerkerd @tsalo @emdupre I think this issue should be closed since we're no longer using v3.2. HOWEVER, I think that this issue should be re-opened if we go back and add v3.2 selection criteria per @tsalo's comments on yesterday's developer call. I would almost consider adding a special v3.2 label so that we can easily find issues like this one if we go back and add compatibility for it. Any thoughts?

**Comment by emdupre** [comment]
I like the idea of a special label for `selcomps` ! I think it will only become more active :)
