### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#98]
Now that we're creating versions of tedana it would be great to also have [a release checklist](https://github.com/poldracklab/fmriprep/wiki/Release-checklist), similar to that used by fMRIPrep. This could go on our RTD site in the [contributing section](http://tedana.readthedocs.io/en/latest/contributing.html). This way, everyone would know what needs to be done to mint an official tedana release !

**Comment by tsalo** [comment]
I don't know if it needs to go in the general contributing section, given that only the maintainer(s) would be responsible for releases. What about a `FOR_MAINTAINERS.md` file or something in the repository?

Then again, making it easily discoverable on the RTD site would make it useful as a learning resource for anyone looking to manage a Python package in a similar manner. Although... maybe it would be better suited for something like [shablona](https://github.com/uwescience/shablona) in that case.

**Comment by KirstieJane** [comment]
I think that’s a good point that only maintainers will *need* to know this information @tsalo but I also want to endorse the idea that others might want to learn from the process. Specifically, contributors should be able to find out what is expected before their work will be released, and the success of tedana will ultimately depend on contributors becoming maintainers....so the more they know the easier that process can be!

I like the idea of a checklist going in CONTRIBUTING and once it’s merged potentially adding a general version to shablona. My suspicion is that it will be much easier to write a specific checklist and make it general, rather than the other way around.
